window.pbjs=window.pbjs||{"que":[]};

function __pgLoadTag(a,b,c){var d=c?c.document:window.document,e=a.tag?a.tag:"script";if(a.id&&d.getElementById(a.id)||a.src&&d.querySelector(e+'[src="'+e.src+'"]')||a.href&&d.querySelector(e+'[href="'+e.href+'"]'))return!1;c=d.createElement(e);e==="script"&&(c.async=!0);b&&c.addEventListener("load",b);for(var f in a)a.hasOwnProperty(f)&&c.setAttribute(f,a[f]);a=d.getElementsByTagName("head")[0]||d.documentElement;a.insertBefore(c,a.firstChild)}__pgLoadTag({tag:"link",rel:"preconnect",href:"https://aax.amazon-adsystem.com"});
__pgLoadTag({src:"https://config.aps.amazon-adsystem.com/configs/3336"});__pgLoadTag({src:"https://client.aps.amazon-adsystem.com/publisher.js"});
window.aps=((a="3336")=>{window._aps=window._aps||new Map;_aps.has(a)||_aps.set(a,{queue:[],store:new Map([["listeners",new Map]])});a={accountID:a,record:function(b,c){return new Promise((d,e)=>{_aps.get(this.accountID).queue.push(new CustomEvent(b,{detail:Object.assign({},c,{resolve:d,reject:e})}))})},read:function(b){return this.record("bootstrap/store/willRead",{name:b}),_aps.get(this.accountID).store.get(b)},run:function(b,c){_aps.get("_system")&&_aps.get("_system").store.get("listeners").has(b)?
this.record(b,c):this.record("bootstrap/run/willDrop",{name:b,detail:c})},react:function(b,c){_aps.get(this.accountID).store.get("listeners").set(b,c);this.record("bootstrap/react/didExecute",{name:b})}};return a.record("bootstrap/version/declare",{version:5}),a})();
((a=window.aps)=>{window.apstag=window.apstag||{init:function(b,c){a.record("legacy/init/enqueue",{config:b,callback:c})},fetchBids:function(b,c){a.record("legacy/fetchBids/enqueue",{bidConfig:b,callback:c})},setDisplayBids:function(){a.run("legacy/setDisplayBids/enqueue",{arguments})},targetingKeys:function(){var b=a.read("legacy/targetingKeys");return b===null||b===void 0?[]:b},rpa:function(b,c,d){a.record("legacy/rpa/enqueue",{tokenConfig:b,callback:c,setCookie:d})},upa:function(b,c,d){a.record("legacy/upa/enqueue",
{tokenConfig:b,callback:c,setCookie:d})},dpa:function(b){a.record("legacy/dpa/enqueue",{callback:b})}};a.record("bootstrapExtAPStag/version/declare",{version:1})})();((a=window.aps)=>{window.apstag=Object.assign({},window.apstag,{queue:{push:function(b){a.record("legacy/queue/push",{callback:b})}}});a.record("bootstrapExtQueue/version/declare",{version:1})})();
((a=window.aps)=>{window.apstag=Object.assign({},window.apstag,{nativeContent:function(){return{enable:function(){a.record("nativeCommerceAds/service/enable")},registerHook:function(b,c){if(b==="nativeCommerceAds.updateClickUrl")a.react("nativeCommerceAds/clickUrl/update",d=>({status:"completed",value:{url:c(d&&d.detail&&d.detail.url?d.detail.url:null,d&&d.detail&&d.detail.element?d.detail.element:null)}}));else throw Error("Unsupported event type");}}}});a.record("bootstrapExtNCA/version/declare",
{version:1})})();


(function(f){function v(a,b,c,d){var e="[POGO]["+(new Date-vb)+"ms]";typeof b==="string"&&b!==""&&(e+="["+b+"]",b=c,c=d,d=null);e+=" "+a;Ra.push({time:(new Date).toString(),msg:e,p1:""+b,p2:""+c,p3:""+d});Y&&(b&&c&&d?console.log(e,b,c,d):b&&c?console.log(e,b,c):b?console.log(e,b):console.log(e))}function wb(a){if(a.indexOf("pglog-")===0){var b=t.querySelector("iframe#"+a);a=t.querySelector("form#"+a+"-form");if(b&&a){var c=t.createElement("div"),d=c.style;d.position="fixed";d.top="10vh";d.right="2%";
d.zIndex="1000000000001";d.padding="2rem";d.backgroundColor="#F2F2F2";d.fontSize="1.5rem";d.color="#000";d.borderRadius="5px";d.border="4px solid #000";c.innerText="Ad information submitted to the Pogo Team. Thank you!";t.body.appendChild(c);setTimeout(function(){c.remove()},6E3)}b&&b.remove();a&&a.remove()}}function xb(){la();for(var a="pglog-"+yb(),b={pogodebug:Ra,pogoconfig:f.PogoConfig?f.PogoConfig:!1,pogometa:f.Pogo.getMeta(),pogoslots:q,targeting:{},adslots:[],viewport:ca,url:f.location.href,
referrer:t.referrer,idx:a,html:t.documentElement.outerHTML},c=googletag.pubads(),d=c.getTargetingKeys(),e=0;e<d.length;e++)b.targeting[d[e]]=c.getTargeting(d[e]);c=c.getSlots();for(e=0;e<c.length;e++)d=c[e],d={id:d.getSlotElementId(),sid:d.getSlotId().toString(),adunit:d.getAdUnitPath(),targeting:d.getTargetingMap(),sizes:d.getSizes(),responseInfo:d.getResponseInformation(),html:d.getHtml(),contentUrl:d.getContentUrl()},b.adslots.push(d);var k=function(){var m=t.createElement("iframe");m.style.display=
"none";t.body.appendChild(m);m.id=a;m.contentWindow.name=a;m=t.createElement("form");m.id=a+"-form";m.target=a;m.action="https://pg.ziffstatic.com/pglog";m.method="POST";var h=t.createElement("input");h.type="hidden";h.name="payload";h.value=JSON.stringify(b);m.appendChild(h);document.body.appendChild(m);m.submit()};try{navigator.mediaDevices.getDisplayMedia({video:{displaySurface:"browser"},audio:!1,preferCurrentTab:!0,selfBrowserSurface:"include",surfaceSwitching:"include",monitorTypeSurfaces:"include"}).then(function(m){var h=
t.createElement("canvas"),g=h.getContext("2d"),l=t.createElement("video");l.srcObject=m;g.drawImage(l,0,0,window.width,window.height);h=h.toDataURL("image/jpeg");m.getTracks().forEach(p=>p.stop());b.screenshot=h;k()})}catch(m){console.error("Screenshot error: "+m),k()}}function sa(a,b){a=String(a).toString();a.normalize&&(a=a.normalize("NFD"));a=a.replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9-_ \.\/]/g,"").replace(/--/g,"-").replace(/--/g,"-").replace(",","");return a=b?a.replace(/[\s+]/g,
"-").replace(/--/g,"-").replace(/--/g,"-"):a.replace(/[\s+]/g,"_").replace(/__/g,"_").replace(/__/g,"_")}function ta(a){return sa(a,!0)}function U(a){f.googletag.cmd.push(a)}function R(a){f.pbjs&&f.pbjs.version?a():(f.pbjs=f.pbjs||{},f.pbjs.que=f.pbjs.que||[],f.pbjs.que.push(a))}function zb(a){function b(w){var u,C="";for(u=0;u<=3;u++)C+="0123456789abcdef".charAt(w>>u*8+4&15)+"0123456789abcdef".charAt(w>>u*8&15);return C}function c(w,u){var C=(w&65535)+(u&65535);return(w>>16)+(u>>16)+(C>>16)<<16|
C&65535}function d(w,u,C,x,P,G){w=c(c(u,w),c(x,G));return c(w<<P|w>>>32-P,C)}function e(w,u,C,x,P,G,J){return d(u&C|~u&x,w,u,P,G,J)}function k(w,u,C,x,P,G,J){return d(u&x|C&~x,w,u,P,G,J)}function m(w,u,C,x,P,G,J){return d(C^(u|~x),w,u,P,G,J)}var h=function(w){var u,C=(w.length+8>>6)+1,x=Array(C*16);for(u=0;u<C*16;u++)x[u]=0;for(u=0;u<w.length;u++)x[u>>2]|=w.charCodeAt(u)<<u%4*8;x[u>>2]|=128<<u%4*8;x[C*16-2]=w.length*8;return x}(a),g=1732584193,l=-271733879,p=-1732584194,r=271733878;for(a=0;a<h.length;a+=
16){var Q=g;var H=l;var D=p;var V=r;g=e(g,l,p,r,h[a+0],7,-680876936);r=e(r,g,l,p,h[a+1],12,-389564586);p=e(p,r,g,l,h[a+2],17,606105819);l=e(l,p,r,g,h[a+3],22,-1044525330);g=e(g,l,p,r,h[a+4],7,-176418897);r=e(r,g,l,p,h[a+5],12,1200080426);p=e(p,r,g,l,h[a+6],17,-1473231341);l=e(l,p,r,g,h[a+7],22,-45705983);g=e(g,l,p,r,h[a+8],7,1770035416);r=e(r,g,l,p,h[a+9],12,-1958414417);p=e(p,r,g,l,h[a+10],17,-42063);l=e(l,p,r,g,h[a+11],22,-1990404162);g=e(g,l,p,r,h[a+12],7,1804603682);r=e(r,g,l,p,h[a+13],12,-40341101);
p=e(p,r,g,l,h[a+14],17,-1502002290);l=e(l,p,r,g,h[a+15],22,1236535329);g=k(g,l,p,r,h[a+1],5,-165796510);r=k(r,g,l,p,h[a+6],9,-1069501632);p=k(p,r,g,l,h[a+11],14,643717713);l=k(l,p,r,g,h[a+0],20,-373897302);g=k(g,l,p,r,h[a+5],5,-701558691);r=k(r,g,l,p,h[a+10],9,38016083);p=k(p,r,g,l,h[a+15],14,-660478335);l=k(l,p,r,g,h[a+4],20,-405537848);g=k(g,l,p,r,h[a+9],5,568446438);r=k(r,g,l,p,h[a+14],9,-1019803690);p=k(p,r,g,l,h[a+3],14,-187363961);l=k(l,p,r,g,h[a+8],20,1163531501);g=k(g,l,p,r,h[a+13],5,-1444681467);
r=k(r,g,l,p,h[a+2],9,-51403784);p=k(p,r,g,l,h[a+7],14,1735328473);l=k(l,p,r,g,h[a+12],20,-1926607734);g=d(l^p^r,g,l,h[a+5],4,-378558);r=d(g^l^p,r,g,h[a+8],11,-2022574463);p=d(r^g^l,p,r,h[a+11],16,1839030562);l=d(p^r^g,l,p,h[a+14],23,-35309556);g=d(l^p^r,g,l,h[a+1],4,-1530992060);r=d(g^l^p,r,g,h[a+4],11,1272893353);p=d(r^g^l,p,r,h[a+7],16,-155497632);l=d(p^r^g,l,p,h[a+10],23,-1094730640);g=d(l^p^r,g,l,h[a+13],4,681279174);r=d(g^l^p,r,g,h[a+0],11,-358537222);p=d(r^g^l,p,r,h[a+3],16,-722521979);l=d(p^
r^g,l,p,h[a+6],23,76029189);g=d(l^p^r,g,l,h[a+9],4,-640364487);r=d(g^l^p,r,g,h[a+12],11,-421815835);p=d(r^g^l,p,r,h[a+15],16,530742520);l=d(p^r^g,l,p,h[a+2],23,-995338651);g=m(g,l,p,r,h[a+0],6,-198630844);r=m(r,g,l,p,h[a+7],10,1126891415);p=m(p,r,g,l,h[a+14],15,-1416354905);l=m(l,p,r,g,h[a+5],21,-57434055);g=m(g,l,p,r,h[a+12],6,1700485571);r=m(r,g,l,p,h[a+3],10,-1894986606);p=m(p,r,g,l,h[a+10],15,-1051523);l=m(l,p,r,g,h[a+1],21,-2054922799);g=m(g,l,p,r,h[a+8],6,1873313359);r=m(r,g,l,p,h[a+15],10,
-30611744);p=m(p,r,g,l,h[a+6],15,-1560198380);l=m(l,p,r,g,h[a+13],21,1309151649);g=m(g,l,p,r,h[a+4],6,-145523070);r=m(r,g,l,p,h[a+11],10,-1120210379);p=m(p,r,g,l,h[a+2],15,718787259);l=m(l,p,r,g,h[a+9],21,-343485551);g=c(g,Q);l=c(l,H);p=c(p,D);r=c(r,V)}return b(g)+b(l)+b(p)+b(r)}function W(a,b,c){typeof a==="string"&&(a={src:a});var d=c?c.document:t,e=a.tag?a.tag:"script";if(!(a.id&&d.getElementById(a.id)||a.src&&d.querySelector(e+'[src="'+e.src+'"]')||a.href&&d.querySelector(e+'[href="'+e.href+'"]'))){c=
d.createElement(e);e==="script"&&(c.async=!0);b&&c.addEventListener("load",b);for(var k in a)a.hasOwnProperty(k)&&c.setAttribute(k,a[k]);b=d.getElementsByTagName("head")[0]||d.documentElement;b.insertBefore(c,b.firstChild)}}function Sa(a){return(a=t.cookie.match("(^|;)\\s*"+a+"\\s*=\\s*([^;]+)"))?a.pop():""}function yb(){return"xxxxxxxxxxxyxxxxxxxxx".replace(/[xy]/g,function(a){var b=Math.random()*16|0;return(a=="x"?b:b&3|8).toString(16)})}function Ab(a){for(var b=1;;){var c=a+"-"+b;if(!t.getElementById(c))return c;
b++}}function X(a,b){a=Array.isArray(a)?a.map(ta):ta(a);return b?String(a):a}function Ta(){try{return typeof top.document.hidden!=="undefined"?top.document.hidden.toString():top.document.hasFocus()?"false":"true"}catch(a){return typeof t.hidden!=="undefined"?t.hidden.toString():t.hasFocus()?"false":"true"}}function Ua(){try{S=t.cookie.match(/geoCC=([^;&]+)/)[1].toUpperCase()}catch(b){}try{t.cookie.match(/geoRC=([^;&]+)/)[1].toUpperCase()}catch(b){}if(f.OOKLA)try{var a=f.OOKLA.globals.location;a.countryCode&&
(S=a.countryCode)}catch(b){}f.zdconsent&&f.zdconsent.geoCC&&(S=f.zdconsent.geoCC)}function Va(a,b){S=a?a.toUpperCase().replace("UK","GB"):"";b&&a.toUpperCase();ua()}function ua(){S||Ua();f.zdconsent&&f.zdconsent.inited?aa=f.zdconsent.gdprApplies:S&&(aa=/be|bg|cz|dk|de|ee|ie|el|es|fr|hr|it|cy|lv|lt|lu|hu|mt|nl|at|pl|pt|ro|si|sk|fi|se|gb|uk|unk|ch/i.test(S)?!0:!1);va=aa?"1---":t.cookie.indexOf("opt_out=")!==-1?"1YYY":"1YNY";f.__uspapi&&f.__uspapi("getUSPData",1,function(b){b.uspString&&(va=b.uspString)});
if(!(!aa||f.OneTrustTCFStub||f.zdconsent&&f.zdconsent.inited)){if(f.__tcfapi&&!f.__tcfapi.zdStub)try{delete f.__tcfapi}catch(b){f.__tcfapi=null}f.OneTrustTCFStub=function(){var b={};return b.iabType=null,b.iabTypeAdded=!0,b.intializeIabStub=function(){b.iabType="IAB2";var c=window;void 0===c.__tcfapi&&(window.__tcfapi=b.executeTcfApi);b.addIabFrame();c.receiveOTMessage=b.receiveIabMessage;(c.attachEvent||window.addEventListener)("message",c.receiveOTMessage,!1)},b.addIabFrame=function(){var c=window;
c.frames.__tcfapiLocator||(c.document.body?b.addLocator("__tcfapiLocator","CMP"):setTimeout(b.addIabFrame,5))},b.addLocator=function(c,d){var e=window,k=e.document.createElement("iframe");k.style.display="none";k.name=c;k.setAttribute("title",d+" Locator");e.document.body.appendChild(k)},b.receiveIabMessage=function(c){var d,e,k,m="string"==typeof c.data,h={};try{h=m?JSON.parse(c.data):c.data}catch(g){}h.__tcfapiCall&&"IAB2"===b.iabType&&(d=h.__tcfapiCall.callId,e=h.__tcfapiCall.command,k=h.__tcfapiCall.parameter,
h=h.__tcfapiCall.version,b.executeTcfApi(e,k,function(g,l){g={__tcfapiReturn:{returnValue:g,success:l,callId:d,command:e}};c&&c.source&&c.source.postMessage&&c.source.postMessage(m?JSON.stringify(g):g,"*")},h))},b.executeTcfApi=function(){for(var c=[],d=0;d<arguments.length;d++)c[d]=arguments[d];if(!c.length)return window.__tcfapi.a||[];d=c[0];var e=c[1],k=c[2];c=c[3];"function"==typeof k&&d&&("ping"===d?b.getPingRequest(k):b.addToQueue(d,e,k,c))},b.addToQueue=function(c,d,e,k){var m=window;m.__tcfapi.a=
m.__tcfapi.a||[];m.__tcfapi.a.push([c,d,e,k])},b.getPingRequest=function(c,d){var e;c&&(e=(d={},!1),"IAB2"!==b.iabType&&"IAB2V2"!==b.iabType||(d={gdprApplies:!0,cmpLoaded:!1,cmpStatus:"stub",displayStatus:"stub",apiVersion:"2.0",cmpVersion:void 0,cmpId:void 0,gvlVersion:void 0,tcfPolicyVersion:void 0},e=!0),c(d,e))},b.getConsentDataRequest=function(c){var d=!1;try{d=window.document.cookie.match(/eupubconsent=([^;&]+)/)[1]}catch(e){}c&&d&&c({gdprApplies:1,hasGlobalScope:!1,consentData:d},!0)},b.intializeIabStub(),
b}();if(f.__tcfapiEventListeners)for(var a=0;a<f.__tcfapiEventListeners.length;a++)f.__tcfapi("addEventListener",2,f.__tcfapiEventListeners[a])}ma=aa&&Wa||f.zdconsent&&f.zdconsent.optinApplies?!0:f.zdconsent&&!f.zdconsent.inited?!0:!1}function Fa(a){var b=a=null,c=f.__ZD_CPID_?f.__ZD_CPID_:null,d=f.__ZD_SEG_?f.__ZD_SEG_:null,e=f.__ZD_USEG_?f.__ZD_USEG_:null,k=null;f.zd&&f.zd.core&&(f.zd.core.pageData&&(f.zd.core.pageData.zdid&&(c=f.zd.core.pageData.zdid),f.zd.core.pageData.pageviewid&&(k=f.zd.core.pageData.pageviewid),
f.zd.core.pageData.pageSegments&&(d=f.zd.core.pageData.pageSegments),f.zd.core.pageData.adParams&&f.zd.core.pageData.adParams.zdbb&&(a=f.zd.core.pageData.adParams.zdbb)),f.zd.core.userData&&(f.zd.core.userData.ppid&&(b=f.zd.core.userData.ppid),f.zd.core.userData.zdbb&&(a=f.zd.core.userData.zdbb),f.zd.core.userData.userSegments&&(e=f.zd.core.userData.userSegments)));a||(a=Sa("h_zdbb"));a||(a=Sa("fpid"));c||(c=f.__ZD_CPID_=zb("http://"+da+f.location.pathname.toLowerCase()));return{zdbb:a,ppid:b,zdid:c,
pvId:k,p2:d,useg:e}}function Bb(){var a=[],b=Fa();(b=b.zdbb?b.zdbb:b.ppid)&&a.push({id:b,atype:1,ext:{stype:"ppuid"}});return a.length?[{source:"ziffdavis.com",uids:a}]:[]}function Ga(a,b){f.googletag.cmd.push(function(){var c=na?"t1":"t0";void 0!==a&&(c+=a?"-e1":"-e0");var d=f.googletag.pubads();d.setTargeting("li-module-enabled",c);d.setTargeting("liact",na?"on":"off")})}function Cb(){try{var a=["8="+encodeURIComponent(f.location.href.split("?")[0]),"9="+encodeURIComponent(da),"12="+encodeURIComponent(Ha)];
f.__ZDU&&f.__ZDU.sha256&&a.push("1="+f.__ZDU.sha256);f.OOKLA&&f.OOKLA.globals&&f.OOKLA.globals.ip&&a.push("10="+encodeURIComponent(f.OOKLA.globals.id));return btoa(a.join("&"))}catch(b){}return""}function Db(){f.pbjs&&f.pbjs.que&&!f.__pogopubx&&(f.pbjs.que=[]);R(function(){var a=A?450:350;a=500;var b={buckets:[{max:30,increment:.01,precision:2},{max:40,increment:.1},{max:90,increment:1}]};b={buckets:[{max:20,increment:.01,precision:2},{max:35,increment:.1},{max:50,increment:.5},{max:120,increment:1}]};
var c={syncEnabled:!0,syncsPerBidder:5,auctionDelay:a,filterSettings:{all:{bidders:"*",filter:"include"}},topics:{maxTopicCaller:4,bidders:[{bidder:"pubmatic",iframeURL:"https://ads.pubmatic.com/AdServer/js/topics/topics_frame.html"},{bidder:"openx",iframeURL:"https://pa.openx.net/topics_frame.html"}]},userIds:[{name:"id5Id",params:{partner:n.id5,canCookieSync:!0,pd:Cb()},storage:{type:"html5",name:"id5id",expires:90,refreshInSeconds:28800}},{name:"criteo"},{name:"pubProvidedId",params:{eidsFunction:Bb}}]};
if(aa||(S&&/us|ca/i.test(S))===!1)n.prebidLiveIntentId=!1,n.prebidLiveRampId=!1,f.liModuleEnabled=!1;if(n.prebidLiveIntentId)if(na=Math.random()<.95,f.liModuleEnabled=na){c.auctionDelay=a*2;c.userIds.unshift({name:"liveIntentId",emailHash:f.__ZDU&&f.__ZDU.md5?f.__ZDU.md5:null,params:{publisherId:n.prebidLiveIntentId,requestedAttributesOverrides:{uid2:!0,index:!0,bidswitch:!0,medianet:!0,magnite:!0,openx:!0,pubmatic:!0,thetradedesk:!0,sovrn:!0,vidazoo:!0,sonobi:!0,sharethrough:!0,triplelift:!0}},storage:{type:"html5",
name:"__tamLIResolveResult",expires:3}});Ga();var d=null;pbjs.onEvent("auctionInit",function(e){d=e.adUnits&&e.adUnits.some(k=>k.bids&&k.bids.some(m=>m.userIdAsEids&&m.userIdAsEids.some(h=>h.source==="liveintent.com"||h.uids&&h.uids.some(g=>g.ext&&g.ext.provider==="liveintent.com"))));Ga(d)})}else Ga();f._qevents&&c.userIds.push({name:"quantcastId"});n.prebidLiveRampId&&(c.userIds.push({name:"identityLink",params:{pid:""+n.prebidLiveRampId},storage:{type:"cookie",name:"idl_env",expires:15,refreshInSeconds:1800}}),
c.userIds.push({name:"pairId",params:{liveramp:{storageKey:"_lr_pairId"}}}));n.prebidUnifiedId&&c.userIds.push({name:"unifiedId",params:{partner:n.prebidUnifiedId},storage:{type:"cookie&html5",name:"pbjs-unifiedid",expires:60,refreshInSeconds:3600}});a={deviceAccess:!0,debugging:{enabled:!1},enableSendAllBids:!0,useBidCache:!0,minBidCacheTTL:35,eventHistoryTTL:60,disableAjaxTimeout:!0,priceGranularity:b,pageUrl:ea,rubicon:{singleRequest:!0},ix:{detectMissingSizes:!0},criteo:{fastBidVersion:"latest"},
enableTIDs:!0,userSync:c,gptPreAuction:{enabled:!0,useDefaultPreAuction:!0},cache:{url:"https://prebid.adnxs.com/pbc/v1/cache"},consentManagement:{usp:{cmpApi:"static",timeout:50,consentData:{getUSPData:{uspString:va}}}}};navigator.cookieDeprecationLabel&&navigator.cookieDeprecationLabel.getValue&&(a.paapi={enabled:!0,defaultForSlots:1});window.zdconsent||typeof window.__uspapi!=="function"||(a.consentManagement.usp={cmpApi:"iab"});typeof window.__tcfapi==="function"&&(a.consentManagement.gdpr={cmpApi:"iab",
timeout:2E3,defaultGdprScope:!1});typeof window.__gpp==="function"&&(a.consentManagement.gpp={cmpApi:"iab",timeout:2E3});n.prebid.teads&&(a.bidCacheFilterFunction=function(e){return e.bidder!=="teads"});Y===3&&(a.debugging={enabled:!0,bids:[{cpm:50}]});try{pbjs.bidderSettings.standard=pbjs.bidderSettings.standard||{},pbjs.bidderSettings.standard.storageAllowed=!0}catch(e){console.log(e)}pbjs.setConfig(a);n.prebidLiveIntentId&&na&&pbjs.refreshUserIds({submoduleNames:["liveIntentId"]})});Xa()}function Eb(){var a=
f.document.querySelector('link[rel="canonical"]');a&&(a=a.href);a||(a=f.location.href.split("?")[0]);return a}function Ya(a){var b=["speedtest","speedtest.com",E,y];N&&N.length&&(b=b.concat(N));b=b.filter(function(e,k){return e&&e!==""&&b.indexOf(e)===k?!0:!1});var c={site:{name:"speedtest",domain:da,ref:t.referrer,mobile:1,privacypolicy:1,kwarray:b,page:Eb(),content:{language:"en",url:f.location.href.split("?")[0],title:t.title.split("|")[0],kwarray:b,context:5},publisher:{name:"Ziff Davis"},ext:{sitetaxonomy:E?
E:y,data:{site:"speedtest",adunit:E?E:y}}}};a&&n.amazonCommerce&&(c.site.publisher.id="844746f9-e5c4-436b-8d57-0bfc28762c63");if(M){M.kwarray&&(c.site.kwarray=M.kwarray);M.context&&(c.site.content.context=M.context);var d=[];c.site.cattax=7;c.site.content.cattax=7;M.site&&(c.site.cat=M.site,d=d.concat(M.site));M.category&&M.category[E]&&(c.site.sectioncat=M.category[E],c.site.pagecat=M.category[E],c.site.content.cattax=7,c.site.content.cat=M.category[E],d=d.concat(M.category[E]));U(function(){d&&
d.length&&googletag.setConfig({pps:{taxonomies:{IAB_CONTENT_2_2:{values:d.slice(0,10)}}}})})}return a?{}:c}function Xa(){R(function(){pbjs.setConfig({ortb2:Ya()})})}function Fb(a){if(n.video&&n.videoPrebid){var b=a.adunitId?a.adunitId:"player",c=a.vp&&a.vp.vpmute?!0:!1,d=a.vp&&a.vp.vpa?!0:!1,e=a.vp&&a.vp.cust_params&&a.vp.cust_params.pogo&&a.vp.cust_params.pogo==="outstream"?!0:!1;e&&!a.iabPos&&(iabPos=3);var k=[3];d&&c?k=[6]:d&&(k=[5]);d=A?640:854;var m=A?480:640,h=a.vp&&a.vp.iu?a.vp.iu:a.video.iu,
g={code:b,ortb2Imp:{ext:{gpid:h,data:{pbadslot:h}}},mediaTypes:{video:{pos:a.iabPos?a.iabPos:3,placement:1,plcmt:c?2:1,api:[2,6,7,8],context:"instream",playerSize:[d,m],mimes:["video/mp4","video/webm","application/javascript"],protocols:[2,3,5,6,7,8],playbackmethod:k,linearity:1,minduration:3,maxduration:e?300:30,startdelay:0,boxingallowed:1,w:d,h:m}},bids:[]};if(Za[b])R(function(){for(var p=0;p<pbjs.adUnits.length;p++){var r=pbjs.adUnits[p];r.code&&r.code===b&&(pbjs.adUnits[p].mediaTypes.video=g.mediaTypes.video)}});
else{for(var l in n.videoPrebid)n.videoPrebid.hasOwnProperty(l)&&(a=null,c=n.videoPrebid[l],l==="appnexus"?a={placementId:parseInt(c.id),frameworks:[2,6]}:l==="rubicon"?a={accountId:c.accountId,siteId:c.siteId,zoneId:c.id,video:{size_id:201,language:"en"}}:l==="ttd"?a={supplySourceId:"ziffdavis",publisherId:c.id}:l==="pubmatic"?a={publisherId:String(c.id),adSlot:c.adSlot?String(c.adSlot):b}:l==="minutemedia"?a={org:String(c.id)}:l==="triplelift"?a={inventoryCode:String(c.id)}:l==="sharethrough"?a=
{pkey:String(c.id)}:l==="ix"?a={siteId:String(c.id)}:l==="openx"?a={delDomain:"ookla-d.openx.net",unit:c.id}:l==="medianet"?a={cid:c.id,crid:c.crid,video:g.mediaTypes.video}:l==="sovrn"?a={tagid:c.id}:l==="kargo"?a={placementId:c.id}:l==="connatix"?(a={placementId:c.id},b&&b!=="player"&&(a.viewabilityContainerIdentifier="#"+b)):l==="amx"?a={tagId:c.id}:l==="teads"?a={pageId:c.id,placementId:c.placementId}:l==="seedtag"?(a={publisherId:c.publisherId,adUnitId:c.id,placement:"inStream"},f.__tcfapi||
(a=!1)):l==="rise"?a={org:c.id}:l==="yahooAds"&&(a={pubId:c.id}),a&&g.bids.push({bidder:l,params:a}));R(function(){pbjs.addAdUnits(g)});Za[b]=!0}}}function Gb(a){var b=q[a],c=b.prebid;if(c){var d=[],e=A?"mobile":"desktop",k=b.sizes&&Array.isArray(b.sizes[0])?b.sizes[0][0]:null,m=null;k&&(k>900?m="billboard":k>=728?m="leaderboard":A&&(m="mobile"));for(var h in c)if(c.hasOwnProperty(h)){k=null;var g=c[h];c[h][e]?g=c[h][e]:b.id&&c[h][b.id]?g=c[h][b.id]:b.type&&c[h][b.type]?g=c[h][b.type]:m&&c[h][m]?
g=c[h][m]:c[h]["default"]&&(g=c[h]["default"]);if(h==="appnexus")k={placementId:parseInt(g.id),allowSmallerSizes:!0,position:b.atf?"above":"below",supplyType:A?"mobile_web":"web"};else if(h==="amx")k={tagId:g.id};else if(h==="ix")k={siteId:g.id,id:b.adunit};else if(h==="openx")k={delDomain:"ookla-d.openx.net",unit:g.id};else if(h==="pubmatic"){if(k={publisherId:String(g.id),adSlot:g.adSlot?String(g.adSlot):b.adunit},!b.sizes[0]||b.sizes[0][0]<300)k=null}else h==="rubicon"?k={accountId:g.accountId,
siteId:g.siteId,zoneId:g.id,position:b.atf?"atf":"btf"}:h==="ttd"?k={supplySourceId:"ziffdavis",publisherId:g.id}:h==="triplelift"?k={inventoryCode:g.id}:h==="33across"?k={siteId:g.id,productId:g.productId?g.productId:"siab"}:h==="criteo"?(k={networkId:g.id},g.pubId&&(k.pubid=g.pubId)):h==="nobid"?k={siteId:g.id}:h==="minutemedia"?k={org:g.id}:h==="kargo"?k={placementId:g.id}:h==="sovrn"?k={tagid:g.id}:h==="medianet"?k={cid:g.id,crid:g.crid}:h==="sharethrough"?k={pkey:String(g.id)}:h==="ogury"?(k=
{assetKey:g.id,adUnitId:g.adunitId},A&&b.type==="sticky"||(k=!1)):h==="kueezrtb"?k={cId:g.id,pId:g.pid}:h==="connatix"?k={placementId:g.id,pos:b.pos,viewabilityContainerIdentifier:"#"+a}:h==="openweb"?k={org:g.org?g.org:"sp_xEkoxAFD",placementId:g.id}:h==="teads"?(k={pageId:g.id,placementId:g.placementId},b.type!=="incontent"&&(k=!1)):h==="seedtag"?(k={publisherId:g.publisherId,adUnitId:g.id,placement:g.placement},B.indexOf("seedtag")===-1&&(k=!1)):h==="rise"?k={org:g.id}:h==="yahooAds"&&(k=g.dcn?
{dcn:g.dcn,pos:g.id}:{pubId:g.id});if(h&&k)if(Array.isArray(k))for(g=0;g<k.length;g++)d.push({bidder:h,params:k[g]});else d.push({bidder:h,params:k})}d&&d.length?R(function(){pbjs.addAdUnits([{code:a,mediaTypes:{banner:{sizes:b.sizes.filter(function(l){return l!=="fluid"})}},bids:d}])}):v("No compatible bidder found for "+a,a)}}function Hb(a){if(a&&a.length){var b=function(){f.pbjs.requestBids({timeout:ba,adUnitCodes:a,bidsBackHandler:function(c,d){v("Prebid Auction Complete",c);U(function(){pbjs.setTargetingForGPTAsync()});
d=0;for(var e=a.length;d<e;d++){var k=a[d];q[k]&&(q[k].prebidStatus=c&&c[k]&&c[k][0]&&c[k][0].cpm?5:10);v("Prebid received&set",k)}fa(a)}})};ma?f.zdconsent.useractioncomplete.push(function(){R(b)}):R(b)}}function $a(){if(!Ia){if(Y===2)try{f.apstag.debug("enableConsole")}catch(c){}var a={pubID:n.amazon?n.amazon:3158,adServer:"googletag",videoAdServer:"DFP",bidTimeout:ba,deals:!0,gdpr:{cmpTimeout:2E3},disableConfigCall:!0},b=Ya("isAmazon");b&&(a.signals={ortb2:b});aa||(a.params={us_privacy:va});f.apstag.init(a);
Ia=!0}}function Ib(a){if(a&&a.length){var b=function(){$a();for(var c={slots:a,timeout:ba},d=0;d<a.length;d++){var e=a[d];q[e]&&q[e].isEmpty===!1&&(c.params={adRefresh:"1"})}try{f.apstag.fetchBids(c,function(k){v("APS Auction Complete",a,k);U(function(){f.apstag.setDisplayBids()});k=[];for(var m=0;m<a.length;m++){var h=a[m].slotID;q[h]&&(q[h].amazonStatus=5);k.push(h);v("APS received&set",h)}fa(k)})}catch(k){v("APS bid failed",a,k);c=[];d=0;for(e=a.length;d<e;d++)q[a[d].slotID].amazonStatus=10,c.push(a[d].slotID);
fa(c)}};ma?f.zdconsent.useractioncomplete.push(b):b()}}function ab(){for(var a=t.querySelectorAll("[data-aps-asin]:not([data-pg])"),b=0;b<a.length;b++)a[b].dataset.pg||a[b].setAttribute("data-pg",1);a=t.querySelectorAll("[data-aps-asc-tag]");for(b=0;b<a.length;b++){var c=a[b].dataset.apsAscTag,d=c.replace(/[^a-z0-9_-]/gi,"");c!==d&&(a[b].dataset.apsAscTag=d,a[b].setAttribute("data-aps-asc-tag",d))}}function Jb(){t.querySelector("[data-aps-asin]:not([data-pg]")&&(ab(),$a(),f.apstag.queue.push(function(){n.otcTracker&&
f.apstag.nativeContent().registerHook("nativeCommerceAds.updateClickUrl",function(a,b){b.setAttribute("data-attr-otc",b.href);return n.otcTracker+encodeURIComponent(a)});ab();f.apstag.nativeContent().enable()}))}function Kb(){if(f.googletag&&f.googletag.apiReady){var a=f.googletag.pubads();I={};var b=[],c=[];n.dv&&(b=["ids","bsc","abs"],c=["ABS","IDS","BSC","VLP"]);for(var d=0;d<b.length;d++){var e=a.getTargeting(b[d]);e&&e.length&&(I[b[d]]=e)}if(c.length)for(b=a.getSlots(),d=0;d<b.length;d++){b[d].getTargeting("qt_loaded");
for(var k=0;k<c.length;k++){var m=c[k];I[m]===void 0&&(e=b[d].getTargeting(m))&&e.length&&(I[m]=e,a.setTargeting(m,e))}}I.IDS&&(c=I.IDS==="1"?"true":"false",I.fr=c,a.setTargeting("fr",c));I.BSC&&(c="low",I.BSC.indexOf("80312001")!==-1&&(c="high"),I.BSC.indexOf("80222001")!==-1&&(c="medium"),c&&a.setTargeting("adt",c))}}function Lb(a){if(n.dv){if(!a)return Ja=!0,fa();var b=!1,c=function(){Ja=!0;b&&clearTimeout(b);U(Kb);fa()};f.dvtag.cmd.push(function(){for(var d=0;d<a.length;d++){var e=a[d];f.dvtag.defineSlot(e,
{id:q[e].adunit,sizes:q[e].sizes});q[e].dvStatus=5}});f.dvtag.cmd.push(function(){var d={callback:c,timeout:ba-100,timestamp:(new Date).getTime()};f.dvtag.queueAdRequest(d);b=setTimeout(function(){d.callback=null;c()},d.timeout)})}}function bb(a){v("Setting up auctions for",a);a||(a=Object.keys(q));for(var b=[],c=[],d=[],e=0,k=a.length;e<k;e++){var m=a[e],h=q[m];if(h){var g=!1;h.prebidStatus&&h.prebidStatus<3&&(q[m].prebidStatus=3,c.push(m),g=!0);h.amazonStatus&&h.amazonStatus<3&&(q[m].amazonStatus=
3,b.push({slotID:h.id,slotName:h.adunit,sizes:h.sizes.filter(function(l){return l!=="fluid"})}),g=!0);g&&d.indexOf(m)==-1&&d.push(m)}else v("Missing adlost",m)}ua();c.length&&Hb(c);b.length&&setTimeout(function(){Ib(b)},1);return d.length?!0:!1}function wa(a,b,c,d){d=d?d:n.dfp;b&&b>1&&K[a+"_"+b]&&K[a+"_"+b].dfpname?d=d.replace("#ADUNIT",K[a+"_"+b].dfpname):K[a]&&K[a].dfpname&&(d=d.replace("#ADUNIT",K[a].dfpname));a==="quickslider"&&(a="masthead");d=d.replace("#PAGETEMPLATE",y).replace("#PAGECATEGORY",
sa(E)).replace("#PAGESLUG",xa).replace("#ADUNIT",a).replace("#NPOS",b&&b>1?"_"+b:"").replace("#GENERAL",E==="homepage"?"homepage":"general").replace("#ID",c).replace(/\s/,"");d=d.replace("#DEVICE",A?"mobile":"desktop");return d=d.replace("/homepage_homepage_","/homepage_")}function Mb(a,b,c,d){return a.dataset&&a.dataset.pos&&parseInt(a.dataset.pos)?parseInt(a.dataset.pos):b?b.match(/top|sticky|atf/i)?1:b==="incontent"||b==="main"?d===1&&c<=3?1:3:b==="sidebar"?A?3:d===1?1:6:b==="footer"?5:3:c&&c<=
1||c&&Z&&c<=2?1:3}function ya(a,b){if(!a||!Array.isArray(a))return null;for(var c=0;c<a.length;c++)if(a[c][0]===b[0]&&a[c][1]===b[1])return!0;return!1}function cb(a,b){var c=0,d;for(d in q)if(q.hasOwnProperty(d)&&q[d].sizes)for(var e=0;e<q[d].sizes.length;e++)if(q[d].sizes[e][0]===a&&q[d].sizes[e][1]===b&&t.getElementById(d)){c+=1;break}return c}function db(a,b){for(var c in q)if(q.hasOwnProperty(c)&&q[c].sizes)for(var d=0;d<q[c].sizes.length;d++)if(q[c].sizes[d][0]===a&&q[c].sizes[d][1]===b&&t.getElementById(c)&&
q[c].guaranteedTakeOver)return!0;return!1}function Nb(a,b){typeof a==="string"&&(a=t.getElementById(a));if(a){var c=a.id;if(c&&q[c])return!1;var d=a.clientHeight?!0:typeof a.offsetWidth==="undefined"||a.offsetWidth||a.offsetHeight||!a.getClientRects||a.getClientRects().length?!0:!1;if(d||a.dataset&&a.dataset.forceload){a.dataset&&a.dataset.pogo&&a.dataset.pogo.indexOf("/")===0&&(a.dataset.adunit=a.dataset.pogo,a.dataset.pogo="main");var e=O(a,"pogo","main");if(e!=="disabled"&&e!=="double"&&e!=="outstream"){var k=
Object.keys(q).length+1,m=Object.keys(q).filter(function(V){return q[V].type===e}).length+1;Ob(a,e,m,k);if(!a.__pogoDisable){c||(c=Ab(e),a.id=c);a.dataset.pogo||(a.dataset.pogo=e);var h=Mb(a,e,k,m),g=h===1?!0:!1,l=wa(e,m,c,O(a,"adunit",n.dfp));d=Pb(a,e,m);if(d!==!1){var p=!1;e==="incontent"&&B.indexOf("pogonative")!==-1&&(d=d.concat([[120,20]]));d!=="fluid"&&(n.pogoInterscroller&&(n.pogoInterscroller.slots.indexOf(e)!==-1||e==="top"&&m===2)&&cb(120,90)<n.pogoInterscroller.num?d=d.concat([[120,90]]):
n.pogoMasthead&&typeof n.pogoMasthead==="string"&&e===n.pogoMasthead&&!cb(120,30)&&(d=d.concat([[120,30]]),a.dataset.autorefresh="false",g=p=!0));if(c&&q[c])return q[c];p||(ya(d,[300,600])&&!db(300,600)?p=!0:ya(d,[970,250])&&!db(970,250)&&(p=!0));var r=O(a,"autorefresh",n.autorefresh,e,m);Z&&p&&(r=!1);var Q=O(a,"autorefreshNonDirectOnly",n.autorefreshNonDirectOnly,e,m);Q&&(r=!1);var H=O(a,"targeting",{});k={rfr:"false",pos:g?"atf":"btf",ppos:k,npos:m>10?10:m,pogo:e,divid:c,gto:p?"true":"false"};for(var D in k)k.hasOwnProperty(D)&&
typeof H[D]==="undefined"&&(H[D]=k[D]);q[c]={id:c,adunit:l,type:e,sizes:d,atf:g,guaranteedTakeOver:p,pos:h,collapse:O(a,"collapse",n.collapse,e,m),targeting:H,renderedAt:null,viewableAt:null,autorefresh:r,autorefreshNonDirectOnly:Q,refreshOnEmpty:O(a,"refreshOnEmpty",n.refreshOnEmpty,e,m),refreshOnEmptyCounter:0,autorefreshTimeout:null,numRendered:0,auctionFailsafe:null,prebid:d.length&&d[0]!=="fluid"?O(a,"prebid",n.prebid,e,m):!1,prebidStatus:null,amazon:d.length&&d[0]!=="fluid"?O(a,"amazon",n.amazon,
e,m):!1,amazonStatus:null,dv:O(a,"dv",n.dv,e,m),dvStatus:null,isEmpty:!0,isNonDirect:null,sticky:O(a,"sticky",!1,e,m),showOnRender:O(a,"showonrender",!1,e,m)};q[c].sticky===!0?(a.parentNode.style.position="sticky",a.parentNode.style.top="1rem"):q[c].sticky&&(m=a.closest(q[c].sticky),m.style.position="sticky",m.style.top="1rem");for(D in b)b.hasOwnProperty(D)&&(q[c][D]=b[D]);b=0;for(m=eb.length;b<m;b++)D=eb[b],q[c][D]&&(D==="prebid"&&Gb(c),q[c][D+"Status"]=1);v("Setup POGO ADSLOT - "+e+" - "+d,q[c],
a);return q[c]}}}}else v("Skipping invisible container",a)}}function fb(a,b){if(F)return b(null,!0);var c=a.content?a.content:!1,d=a.playerId;try{c||(c=(f.PogoExcoPlayerApi&&f.PogoExcoPlayerApi[d]?f.PogoExcoPlayerApi[d]:f.ExCoPlayer.connect(d)).getPlaylistItem())}catch(e){console.log("Ex.co Player API error",e)}a={isExco:!0,playerId:d,playType:"click",isMuted:typeof a.muted!=="undefined"?a.muted:!0,isLive:typeof a.isLive!=="undefined"?a.isLive:!1};c&&(a.isRecirculation=typeof c.index!=="undefined"?
c.index:0,c.id&&(a.videoId=c.id),c.title&&(a.title=c.title),c.keywords&&(a.category=c.keywords),c.tags&&(a.tags=c.tags),c.duration&&(a.duration=c.duration));za(a,b)}function Qb(a){a||(a={});var b=a.vastParams?a.vastParams:n.video?Object.assign({},n.video):{},c=a.playerContext?a.playerContext:"";b.iu=b.iu.replace("#PAGETEMPLATE",y).replace("#PAGECATEGORY",sa(E)).replace("#PAGESLUG",xa).replace("#DEVICE",A?"mobile":"desktop").replace("#PLAYERCONTEXT",c).replace("#ID","").replace(/\s/,"");b.iu.slice(-1)===
"/"&&(b.iu=b.iu.slice(0,-1));b.url=ea;b.description_url=ea;b.correlator=gb;typeof b.ad_rule==="undefined"&&(b.ad_rule=0);typeof b.trt==="undefined"&&(b.trt=2);typeof b.vconp==="undefined"&&(b.vconp=1);typeof b.vpa==="undefined"&&(b.vpa="click");c=Fa();c.zdid&&(b.cust_params.zdid=c.zdid);c.zdbb&&(b.ppid=c.zdbb,b.cust_params.zdbb=c.zdbb);c.ppid&&(b.ppid=c.ppid);c.p2&&(b.cust_params.p2=c.p2);c.useg&&(b.cust_params.s=c.useg);c.pvId&&(b.cust_params.pageviewid=c.pvId);c={get:function(h){return null}};try{c=
new URLSearchParams(B)}catch(h){}for(var d=["special","utm_source","utm_campaign","utm_medium"],e=0;e<d.length;e++)c.get(d[e])&&(b.cust_params[d[e]]=c.get(d[e]));b.cust_params.template=y;a.isExco&&(b.cust_params.pogo="exco");a.size&&(b.sz=a.size.replace(",","|").replace(" ","|").replace("v",""));a.vpos&&(b.vpos=a.vpos.toLowerCase());!b.vpa&&a.isOutstream&&(b.vpa="auto");a.playType&&(b.vpa=a.playType.toLowerCase());a.videoId&&(b.vid=a.videoId,b.cust_params.vid=a.videoId);a.cmsId&&(b.cmsid=a.cmsId);
a.isRecirculation&&(b.cust_params.recirc=1);b.plcmt||(b.plcmt=a.isMuted?2:1);b.trt||(b.trt=2);a.isLive&&(b.cust_params.live=1);a.isMuted&&(b.vpmute=1,b.cust_params.muted=!0);a.isInstream&&(b.cust_params.instream=1);a.minAdDuration&&(b.min_ad_duration=a.minAdDuration);a.maxAdDuration&&(b.max_ad_duration=a.maxAdDuration);a.videoDuration&&(b.vid_d=a.videoDuration);b.cust_params.category=a.category?a.category:E;b.cust_params.tags=a.tags?a.tags:N;a.subcategory&&(b.cust_params.subcategory=a.subcategory);
a.videoshow&&(b.cust_params.videoshow=b.cust_params.show=a.videoshow);b.cust_params.trt=b.trt;b.cust_params.aconp=b.aconp;b.cust_params.vpa=b.vpa;if(n.pageTargeting)for(var k in n.pageTargeting)n.pageTargeting.hasOwnProperty(k)&&n.pageTargeting[k]&&(b.cust_params[k]=n.pageTargeting[k]);if(window.googletag&&window.googletag.apiReady)for(k=window.googletag.pubads().getTargetingKeys(),c=0;c<k.length;c++)d=k[c],b.cust_params[d]=window.googletag.pubads().getTargeting(d);if(a.customParams)for(var m in a.customParams)a.customParams.hasOwnProperty(m)&&
(b.cust_params[m]=a.customParams[m]);return b}function ha(a){var b=[],c;for(c in a.cust_params)if(a.cust_params.hasOwnProperty(c)){var d=Array.isArray(a.cust_params[c])?a.cust_params[c].join(","):a.cust_params[c];d&&b.push(c+"="+d)}if(I)for(c in I)I.hasOwnProperty(c)&&(d=Array.isArray(I[c])?I[c].join(","):I[c])&&b.push(c+"="+d);a.cust_params=b.join("&");b=Object.keys(a).map(function(e){return encodeURIComponent(e)+"="+encodeURIComponent(a[e])}).join("&");return(a.cust_params.live?"https://pubads.g.doubleclick.net/gampad/live/ads?":
"https://pubads.g.doubleclick.net/gampad/ads?")+b}function za(a,b){if(F)return b&&b("",!0),"";if(B.indexOf("pogodebug=video")!==-1){var c="iu=/21775744923/external/single_ad_samples&cust_params=sample_ct%3Dlinear&output=vast";B.indexOf("skippable")!==-1&&(c="iu=/21775744923/external/single_preroll_skippable&output=vast");B.indexOf("vmap")!==-1&&(c="iu=/21775744923/external/vmap_ad_samples&cust_params=sample_ar%3Dpreonlybumper&ad_rule=1&output=vmap");B.indexOf("vpaid")!==-1&&(c="iu=/21775744923/external/single_ad_samples&cust_params=sample_ct%3Dlinearvpaid2js&output=vast");
B.indexOf("vmap2")!==-1&&(c="iu=/21775744923/external/vmap_ad_samples&cust_params=sample_ar%3Dpremidpostpod&ad_rule=1&output=vmap&cmsid=496&vid=short_onecue");c="https://pubads.g.doubleclick.net/gampad/ads?"+c+"&sz=640x480&ciu_szs=300x250%2C728x90&gdfp_req=1&unviewed_position_start=1&env=vp&impl=s&correlator=";if(b){setTimeout(function(){b(c,!0)},25);return}return c}var d=Qb(a),e=!1,k=!1;if(!b)return ha(d);var m=a.videoAdunitId?a.videoAdunitId:a.playerId?a.playerId:a.videoId?a.videoId:"player";n.amazon&&
f.apstag&&(e="running");n.videoPrebid&&f.pbjs&&(k="running");if(n.amazon&&f.apstag)try{a=function(){var g={slotID:"player",mediaType:"video",sizes:[[640,360],[640,480]]};n.video&&n.video.floor&&(g.floor={value:n.video.floor,currency:"USD"});f.apstag.fetchBids({slots:[g],timeout:ba*1.4},function(l){if(l&&l.length)for(var p=0;p<l.length;p++)if(l[p].targeting)for(var r in l[p].targeting)l[p].targeting.hasOwnProperty(r)&&(d.cust_params[r]=l[p].targeting[r]);e="done";k&&k!=="done"||b(ha(d),!0)})},ma?f.zdconsent.useractioncomplete.push(a):
a()}catch(g){e="done",console.log("APS Video Error",g),k&&k!=="done"||b(ha(d),!0)}if(n.videoPrebid&&f.pbjs)try{k="running";Fb({adunitId:m,vp:d});var h=function(){f.pbjs.requestBids({adUnitCodes:[m],bidsBackHandler:function(g,l,p){if(g=pbjs.getAdserverTargetingForAdUnitCode(m))for(var r in g){g.hasOwnProperty(r)&&(l=g.hb_bidder?r.replace("_"+g.hb_bidder,""):r,d.cust_params[l]=g[r]);try{d.cust_params.hb_bidder&&d.cust_params.hb_bidder==="rubicon"&&d.cust_params.hb_uuid&&!d.cust_params.hb_uuid_rubicon&&
(d.cust_params.hb_uuid_rubicon=d.cust_params.hb_uuid)}catch(Q){console.log(Q)}}k="done";pbjs.markWinningBidAsUsed({adUnitCode:m});e&&e!=="done"||b(ha(d),!0)},timeout:ba*1.4})};ma?f.zdconsent.useractioncomplete.push(function(){R(h)}):R(h)}catch(g){k="done",console.log("Prebid Video Error",g),e&&e!=="done"||b(ha(d),!0)}e||k||b(ha(d),!0)}function hb(a){typeof a==="string"&&(a=a.split(" "));return a&&a.length?f.googletag.pubads().getSlots().filter(function(b){return a.indexOf(b.getSlotElementId())===
-1?!1:!0}):[]}function Rb(a){var b=f.googletag.pubads().getSlots().filter(function(c){return c.getSlotElementId()===a});return b&&b.length>0?b[0]:null}function oa(a,b){if(a===null)return b||null;if(typeof a["0x0"]==="undefined")return a;b=b||null;var c=0,d;for(d in a)if(a.hasOwnProperty(d)){var e=d.toLowerCase().split("x"),k=parseInt(e[0]);e=parseInt(e[1]);k<=ca[0]&&k>=c&&e<=ca[1]&&(b=a[d],c=k)}return b}function O(a,b,c,d,e){if(b==="prebid"&&f.pbjs&&f.pbjs.DISABLED)return!1;typeof a==="string"&&(a=
t.getElementById(a));if(typeof a.dataset[b]!=="undefined")try{return JSON.parse(a.dataset[b])}catch(k){return a.dataset[b]}return(a=a.id)&&K[a]&&typeof K[a][b]!=="undefined"?oa(K[a][b]):d&&e&&K[d+"_"+e]&&typeof K[d+"_"+e][b]!=="undefined"?oa(K[d+"_"+e][b]):d&&K[d]&&typeof K[d][b]!=="undefined"?oa(K[d][b]):typeof n[b]!=="undefined"?oa(n[b]):c}function Pb(a,b,c){if(a.__pogoAdSize)return a.__pogoAdSize;a=O(a,"sizes",null,b,c);if(typeof a==="string")return a;a=oa(a,[300,250]);Z&&ya(a,[300,250])===!0&&
ya(a,[300,600])===!1&&b!=="top"&&(A||b!=="autopogo")&&(a=a.slice(),a.push([300,600]));return a}function ib(a){var b=t.getElementById("pogo-adhesion");b&&(b.classList.add("closed"),a&&(t.cookie="pogostckftrclsd=1; path=/;"),setTimeout(function(){Aa(["pogo-adhesion-1"]);b.parentNode&&b.parentNode.removeChild(b);b.remove&&b.remove()},650))}function Sb(){if(!F&&n.pogoMasthead&&n.pogoMasthead===!0&&T!=="/ad/feature/year-in-gifts"){var a=t.getElementById("pogo-quickslider");if(!a||!z["pogo-quickslider"]){a||
(a=t.createElement("div"),a.id="pogo-quickslider",a.style.position="absolute",a.style.left="1px",a.style.top="1px",a.style.minWidth="5px",a.style.minHeight="5px",a.style.background="transparent",a.style.zIndex=0x9184e72a065,t.body.insertBefore(a,t.body.firstChild));var b=wa("quickslider",0,"pogo-quickslider");z["pogo-quickslider"]={id:"pogo-quickslider",adslot:null,numRendered:0,isEmpty:!0,guaranteedTakeOver:!0,targeting:{gto:!0,rfr:!1}};n.disableSRA&&pa&&!n.dv&&(z["pogo-quickslider"].numRendered=
1);v("Added Pogo Quickslider/Masthead slot","pogo-quickslider",a);U(function(){var c=f.googletag.defineSlot(b,[120,30],"pogo-quickslider").addService(f.googletag.pubads());c.setTargeting("oop_type","masthead").setTargeting("pos","0").setTargeting("ppos",["0","atf"]).setTargeting("divid","pogo-quickslider").setTargeting("rfr","false").setTargeting("gto","true");z["pogo-quickslider"].adslot=c;f.googletag.display("pogo-quickslider");!pa||Z||n.dv||(v("quickload Quickslider/Masthead slot","pogo-quickslider",
a),f.googletag.pubads().refresh([c]),z["pogo-quickslider"].numRendered=1)})}}}function Tb(){F||n.OOPs&&n.OOPs.length&&n.OOPs.forEach(function(a){var b="pogo-oop-"+a;if(!t.getElementById(b)){var c=document.createElement("div");c.id=b;c.className="pogo-oop";c.style.position="absolute";c.style.bottom="1px";c.style.left="1px";c.style.zIndex=10000002;t.body.appendChild(c);var d=wa(a,0,b);z[b]={id:b,adslot:null,numRendered:0,isEmpty:!0,targeting:{gto:!1,rfr:!1}};U(function(){var e=f.googletag.defineOutOfPageSlot(d,
b).addService(f.googletag.pubads());e.setTargeting("oop_type",a).setTargeting("pos",a).setTargeting("divid",b);f.googletag.display(b);z[b].adslot=e});v("Added GPT OOP",b,c)}})}function Ub(a){a=parseInt(a)/1E3;switch(!0){case a<5:return"0-4";case a<10:return"5-9";case a<15:return"10-14";case a<20:return"15-19";case a<30:return"20-29";case a<40:return"30-39";case a<50:return"40-49";case a<75:return"50-74";case a<100:return"75-99";case a<150:return"100-149";case a<200:return"150-199";case a<250:return"200-249";
default:return"250plus"}}function jb(a){switch(!0){case a<5:return"0-4";case a<10:return"5-9";case a<15:return"10-14";case a<20:return"15-19";case a<30:return"20-29";case a<40:return"30-39";case a<50:return"40-49";case a<60:return"50-59";case a<70:return"60-69";case a<80:return"70-79";case a<90:return"80-89";case a<100:return"90-99";case a<150:return"100-149";case a<200:return"150-199";case a<250:return"200-249";case a<300:return"250-299";case a<400:return"300-399";case a<500:return"400-499";case a<
600:return"500-599";case a<700:return"600-699";case a<800:return"700-799";case a<900:return"800-899";case a<1E3:return"900-999";default:return"1000plus"}}function kb(a,b){a=t.body.classList;Ba=!0;la();a.contains("sthome")||(a.remove("stresults","stshare"),a.add("sthome"),n.autorefresh=n.autorefreshNonDirectOnly=!1,y="homepage",b&&(b=A?500:50,setTimeout(ia,b),setTimeout(L,b+300),setTimeout(L,b+600)))}function lb(){if(!mb){var a=t.querySelector('#container, div[data-view-name="root"], div[data-view-instance-placeholder="root"], body');
a||setTimeout(lb,100);B.indexOf("pogoab")!==-1&&(nb=!0);a.addEventListener("click",function(b){for(var c=b.target,d=a.querySelectorAll("a.js-start-test, a.js-start-test > *, a.btn-restart-test"),e=0;e<d.length;e++){var k=d[e];(c===k||k.contains(c))&&kb(k,b)}});f.addEventListener("message",function(b){if((b=b.data)&&b.event&&b.event&&b.event==="stStage"&&b.stage)if(b.stage==="started"||b.stage==="testButtonClicked")kb(),Ba=!0;else if(b.stage==="finish"||b.stage==="error")Ba=!1,n.autorefreshNonDirectOnly=
35,b=t.body.classList,b.add("stresults"),b.remove("sthome","stshare"),y="results",b=A?1E3:125,setTimeout(ia,b),setTimeout(L,b+200),setTimeout(L,b+500),setTimeout(L,b+1E3),setTimeout(L,b+1500)});t.addEventListener("visibilitychange",function(){if(t.visibilityState&&t.visibilityState==="visible"&&!Ba){var b=[];Object.keys(q).forEach(function(c){q[c].isNonDirect&&b.push(c)});b.length&&setTimeout(function(){ja(b)},1E3)}});mb=!0}}function Ob(a,b,c,d){b==="footer"?(a.setAttribute("data-adunit",A?"/6692/speedtest.net/st_mw_banner":
"/6692/speedtest.net/stnext_lowerboard"),a.setAttribute("data-pos","5")):a.setAttribute("data-pos","1");b=a.id;c=null;b==="stnext_leaderboard"?c={openx:{id:538306129},rubicon:{accountId:11576,siteId:79558,id:373684},ix:{id:184382},appnexus:{id:7724467},pubmatic:{id:159017,adSlot:b},sharethrough:{id:"rmWgQEnhuz7ij4zskq9giJxW"},criteo:{id:11834},yahooAds:{id:"stnext_leaderboard_728x90",dcn:"8a969009017373bfc8dcc112d91b00af"},medianet:{id:"8CUYEJ1S6",crid:"498162527"}}:b==="stnext_skyscraper"?c={openx:{id:538306131},
rubicon:{accountId:11576,siteId:79558,id:373684},ix:{id:184386},appnexus:{id:7724472},pubmatic:{id:159017,adSlot:b},sharethrough:{id:"LS1YWeTnjSb4eek4I3k1sdAM"},criteo:{id:11834},yahooAds:{id:"stnext_skyscraper_160x600",dcn:"8a969009017373bfc8dcc112d91b00af"},medianet:{id:"8CUYEJ1S6",crid:"141447523"}}:b==="stnext_top_rectangle"?c={openx:{id:538306127},rubicon:{accountId:11576,siteId:79558,id:373684},ix:{id:184384},appnexus:{id:7724469},pubmatic:{id:159017,adSlot:b},sharethrough:{id:"lyfPr85svgZNZlzQUSiQltlX"},
criteo:{id:11834},yahooAds:{id:"stnext_top_rectangle_300x250",dcn:"8a969009017373bfc8dcc112d91b00af"},medianet:{id:"8CUYEJ1S6",crid:"265788797"}}:b==="stnext_bottom_rectangle"?c={openx:{id:538306123},rubicon:{accountId:11576,siteId:79558,id:373682},ix:{id:184385},appnexus:{id:7724470},pubmatic:{id:159017,adSlot:b},sharethrough:{id:"w4l7ODDu2qWU2qic0xVuVoZ3"},criteo:{id:11834},yahooAds:{id:"stnext_bottom_rectangle_300x250",dcn:"8a969009017373bfc8dcc112d91b00af"},medianet:{id:"8CUYEJ1S6",crid:"277720419"}}:
b==="stnext_lowerboard"||b==="stnext_footer"?(c={openx:{id:538306126},rubicon:{accountId:11576,siteId:79558,id:373682},ix:{id:184383},appnexus:{id:7724468},pubmatic:{id:159017,adSlot:"stnext_lowerboard"},sharethrough:{id:"9nQhM2YVqftAuHIn1076G9az"},criteo:{id:11834},yahooAds:{id:"stnext_lowerboard_728x90",dcn:"8a969009017373bfc8dcc112d91b00af"},medianet:{id:"8CUYEJ1S6",crid:"342887473"}},A&&(c={openx:{id:556680971},rubicon:{accountId:11576,siteId:413252,id:2324050},ix:{id:785512},appnexus:{id:24419551},
pubmatic:{id:159017,adSlot:"4319099"},sharethrough:{id:"TzOMeTsi3Hr4eLEZMcOTLfaf"},criteo:{id:11834},yahooAds:{id:"st_mw_mrec",dcn:"8a969009017373bfc8dcc112d71600ad"},medianet:{id:"8CUYEJ1S6",crid:"540391151"}})):b==="results_stnext_leaderboard"?c={openx:{id:540589504},rubicon:{accountId:11576,siteId:79558,id:1111152},ix:{id:338774},appnexus:{id:14382749},pubmatic:{id:159017,adSlot:b},sharethrough:{id:"AA5a1w5NXCqIRnnNnS9Skw1k"},criteo:{id:11834},yahooAds:{id:"results_stnext_leaderboard_728x90",dcn:"8a969009017373bfc8dcc112d91b00af"},
medianet:{id:"8CUYEJ1S6",crid:"568151553"}}:b==="results_stnext_right_300x600"?c={openx:{id:540589510},rubicon:{accountId:11576,siteId:79558,id:1111154},ix:{id:346424},appnexus:{id:14382752},pubmatic:{id:159017,adSlot:b},sharethrough:{id:"6Nnlzkj3tJjilKqGtZedxL8e"},criteo:{id:11834},yahooAds:{id:"results_stnext_right_300x600",dcn:"8a969009017373bfc8dcc112d91b00af"},medianet:{id:"8CUYEJ1S6",crid:"721564925"}}:b==="results_stnext_300x250"?c={openx:{id:540589503},rubicon:{accountId:11576,siteId:79558,
id:1111150},ix:{id:338773},appnexus:{id:14382746},pubmatic:{id:159017,adSlot:b},sharethrough:{id:"ThdArDvgtARL8gXDIEUwKMN6"},criteo:{id:11834},yahooAds:{id:"results_stnext_300x250",dcn:"8a969009017373bfc8dcc112d91b00af"},medianet:{id:"8CUYEJ1S6",crid:"183961503"}}:b==="st_mw_banner"?c={openx:{id:556680970},rubicon:{accountId:11576,siteId:413252,id:2324048},ix:{id:785511},appnexus:{id:24419549},pubmatic:{id:159017,adSlot:"4319098"},sharethrough:{id:"fplBeOE3sow8KbKHYfRTRvyh"},criteo:{id:11834},yahooAds:{id:"st_mw_banner",
dcn:"8a969009017373bfc8dcc112d71600ad"},medianet:{id:"8CUYEJ1S6",crid:"915753458"}}:b==="st_mw_eot"&&(c={openx:{id:556680971},rubicon:{accountId:11576,siteId:413252,id:2324050},ix:{id:785512},appnexus:{id:24419551},pubmatic:{id:159017,adSlot:"4319099"},sharethrough:{id:"TzOMeTsi3Hr4eLEZMcOTLfaf"},criteo:{id:11834},yahooAds:{id:"st_mw_mrec",dcn:"8a969009017373bfc8dcc112d71600ad"},medianet:{id:"8CUYEJ1S6",crid:"540391151"}});qa&&(c=!1);c?a.setAttribute("data-prebid",JSON.stringify(c)):a.removeAttribute("data-prebid")}
function ob(){var a=t.body.classList;y==="homepage"?(a.add("sthome"),a.remove("stresults","stshare")):y==="results"?(a.add("stresults"),a.remove("sthome","stshare")):y==="share"&&(a.add("stshare"),a.remove("sthome","stresults"));if(qa&&!t.getElementById("results_stnext_lowerboard")&&(a=t.getElementById("stnext_lowerboard"))&&a.parentNode){var b=t.createElement("div");b.id="results_stnext_lowerboard";b.setAttribute("aria-hidden","true");b.setAttribute("data-pogo","main");a.parentNode.insertBefore(b,
a.nextSibling)}a=t.querySelectorAll('[data-pogo="double"]');for(b=0;b<a.length;b++){var c=a[b];if(!c.querySelector("[data-pogo]")){var d=t.createElement("div");d.setAttribute("data-pogo","largerec");c.appendChild(d);A||(d=t.createElement("div"),d.setAttribute("data-pogo","largerec"),c.appendChild(d))}c.classList.add("pogoDouble")}}function pb(a,b){if(F)return!1;a||(ob(),a="div[data-pogo]");typeof a==="string"&&(a=t.querySelectorAll(a));for(var c=[],d=[],e=[],k=[],m=0,h=a.length;m<h;m++){var g=Nb(a[m]);
g&&(c.push(g),g.guaranteedTakeOver||g.isAtf?d.push(g.id):e.push(g.id),g.dvStatus&&g.dvStatus<3&&(g.dvStatus=3,k.push(g.id)))}if(c.length){U(function(){for(var l,p,r=0,Q=c.length;r<Q;r++){p=c[r];l=Rb(p.id);l||(l=f.googletag.defineSlot(p.adunit,p.sizes,p.id),l=l.addService(f.googletag.pubads()));l.setCollapseEmptyDiv(p.collapse);for(var H in p.targeting)p.targeting.hasOwnProperty(H)&&(p.targeting[H]===null?l.getTargeting(H).length&&l.clearTargeting(H):l.setTargeting(H,X(p.targeting[H])));f.googletag.display(l)}});
ua();n.dv&&k.length&&Lb(k);a=d.concat(e);d=[];for(m=0;m<a.length;m+=6)d.push(a.slice(m,m+6));d.forEach(function(l,p){setTimeout(function(){bb(l)||b||(v("No auction needed - refreshing the ads right away",l),fa(l))},p*300)});return c}}function Aa(a){typeof a==="string"&&(a=a.split(" "));n.prebid&&R(function(){pbjs.removeAdUnit(a)});for(var b=0,c=a.length;b<c;b++){var d=a[b];q[d]&&(q[d].autorefreshTimeout&&f.clearTimeout(q[d].autorefreshTimeout),delete q[d])}U(function(){var e=hb(a);e&&e.length?f.googletag.destroySlots(e):
v("Attempted to destroy non-existant slots",a,e)})}function Vb(){v("All adslots on page destroyed");q={};z={};n.pageTargeting={};n.prebid&&R(function(){pbjs.removeAdUnit()});if(f.googletag&&f.googletag.destroySlots){try{f.googletag.destroySlots()}catch(a){}try{f.googletag.pubadsReady&&f.googletag.pubads().clearTargeting("zdid","special")}catch(a){}t.querySelectorAll("div[id^=google_ads_iframe_]").forEach(function(a){a.remove()})}}function Ka(a){typeof a==="string"&&(a=a.split(" "));a&&a.length||(a=
Object.keys(q));for(var b=[],c=0,d=a.length;c<d;c++){var e=q[a[c]];!e||e.prebidStatus&&e.prebidStatus<5||e.amazonStatus&&e.amazonStatus<5||e.dvStatus&&e.dvStatus<5||b.push(a[c])}return b.length?b:!1}function fa(a){if(n.dv&&!Ja)return!1;a=Ka(a);if(!a||!a.length)return!1;if(Z){var b=a.filter(function(d){return q[d]&&q[d].guaranteedTakeOver&&!q[d].numRendered?!0:!1});if(b.length){var c=Object.keys(q).filter(function(d){return q[d]&&q[d].guaranteedTakeOver&&!q[d].numRendered});if(b.length===c.length)return ka(a)}else return ka(a)}else return ka(a);
return!1}function ka(a){typeof a==="string"&&(a=a.split(" "));a&&a.length||(a=Object.keys(q));for(var b in z)z[b]&&!z[b].numRendered&&(Z&&z[b].guaranteedTakeOver&&!a.filter(function(d){return q[d]&&q[d].guaranteedTakeOver}).length||a.push(b));U(function(){var d=hb(a);if(!d)return v("No GPT ads?",a),!1;for(var e=0,k=d.length;e<k;e++){var m=d[e],h=m.getSlotElementId();if(h=q[h]?q[h]:z[h]?z[h]:null){m.setTargeting("rfr",h.targeting.rfr);if(h.targeting.rfre)m.setTargeting("rfre",h.targeting.rfre);else if(m.getTargeting("rfre").length)try{m.clearTargeting("rfre")}catch(g){}h.targeting.rfr===
"true"&&(h.targeting.gto="false");m.setTargeting("gto",h.targeting.gto)}}f.googletag.pubads().setTargeting("OOF",X(Ta()));f.googletag.pubads().refresh(d);v("GPT Refresh ads",a,d)});for(b=0;b<a.length;b++){var c=a[b];if(c=q[c]?q[c]:z[c]?z[c]:null)c.numRendered+=1}}function ja(a,b){typeof a==="string"&&(a=a.split(" "));a&&a.length||(a=Object.keys(q));typeof a[0]!=="undefined"&&a[0].getSlotElementId&&(a=a.map(function(k){return k.getSlotElementId()}));v("Adrefresh Requested",a);for(var c=0,d=a.length;c<
d;c++){var e=a[c];if(e=q[e]?q[e]:z[e]?z[e]:null)e.autorefreshTimeout&&(f.clearTimeout(e.autorefreshTimeout),e.autorefreshTimeout=null),e.isEmpty||(e.targeting.rfr="true",e.targeting.gto="false"),e.renderedAt=null,e.viewableAt=null,e.isNonDirect=null}b?(v("Immediate Refresh",a),ka(a)):!bb(a)&&Ka(a)&&(v("No auction needed - refreshing",a),ka(a))}function la(a){typeof a==="string"&&(a=a.split(" "));a&&a.length||(a=Object.keys(q));typeof a[0]!=="undefined"&&a[0].getSlotElementId&&(a=a.map(function(e){return e.getSlotElementId()}));
for(var b=0,c=a.length;b<c;b++){var d=a[b];q[d]&&(q[d].autorefreshTimeout&&(f.clearTimeout(q[d].autorefreshTimeout),q[d].autorefreshTimeout=null),q[d].autorefresh=!1)}}function Wb(a){typeof a==="string"&&(a=a.split(" "));if(a&&a.length){typeof a[0]!=="undefined"&&a[0].getSlotElementId&&(a=a.map(function(e){return e.getSlotElementId()}));for(var b=0,c=a.length;b<c;b++){var d=t.getElementById(a[b]);d&&d.classList.add("noAdvLabel")}}}function qb(){var a=f.googletag.pubads();a.setTargeting("template",
X(y));a.setTargeting("category",X(E));a.setTargeting("env",X(da));a.setTargeting("OOF",X(Ta()));var b=t.referrer;if(b&&b!=="")try{b=b.split("://")[1].split("/")[0],b=b.split(".").reverse().splice(0,2).reverse().join(".")}catch(k){}b&&da.indexOf(b)!==-1||a.setTargeting("fito","true");a.setTargeting("ref",X(b));a.set("page_url",ea);b=Fa();b.p2&&a.setTargeting("p2",b.p2);b.useg&&a.setTargeting("s",b.useg);(b.ppid||b.zdbb)&&a.setPublisherProvidedId(b.ppid?b.ppid:b.zdbb);var c=a.getTargeting("zdid");c&&
c.length||!b.zdid||a.setTargeting("zdid",b.zdid);(c=a.getTargeting("zdbb"))&&c.length||!b.zdbb&&!b.ppid||a.setTargeting("zdbb",b.zdbb?b.zdbb:b.ppid);b={get:function(k){return null}};try{b=new URLSearchParams(B)}catch(k){}c=["special","utm_source","utm_campaign","utm_medium"];for(var d=0;d<c.length;d++)b.get(c[d])?a.setTargeting(c[d],X(b.get(c[d]))):a.getTargeting(c[d]).length&&a.clearTargeting(c[d]);B.indexOf("pogo_zdid")!==-1&&console.log("%cThis page ZDID is "+zdid,"color: red; font-weight: bold; font-size: 30px;");
!N||!N.length||n.pageTargeting&&n.pageTargeting.content||a.setTargeting("content",N);if(n.pageTargeting)for(var e in n.pageTargeting)n.pageTargeting.hasOwnProperty(e)&&(n.pageTargeting[e]===null?a.getTargeting(e).length&&a.clearTargeting(e):a.setTargeting(e,X(n.pageTargeting[e])))}function La(a){if(!a||a==="")return"";Array.isArray(a)&&(a=a.join(" > "));return ta(a.replace(/&#039;/gi,"").replace(/&amp;/gi,"-").replace("-page",""))}function Ma(a){if(!a||a==="")return[];var b=[];a=a.split?a.split(","):
a;for(var c=0,d=a.length;c<d;c++)if(a[c]){var e=ta(a[c]);e&&e!==""&&b.indexOf(e)===-1&&b.push(e)}return b}function L(a){Ca||(v("Early _runPogoAdslots call - ignoring"),Na());v("Pogo DetectAdslots invoked");ra||Oa();if(!ra)return setTimeout(L,100),!1;F=f.OOKLA&&f.OOKLA.globals&&f.OOKLA.globals.configs&&f.OOKLA.globals.configs.ads===!1?!0:!1;if(B.indexOf("zmg_ads")!==-1||B==="?nsp")F=!0;Ha.match(/Typhoeus|python-requests|github/gi)&&(F=!0);if(n.disableAds&&T)for(var b=0;b<n.disableAds.length;b++)T.indexOf(n.disableAds[b])===
0&&(F=!0);t.body&&t.body.classList&&(F?t.body.classList.add("pgDsbld"):t.body.classList.remove("pgDsbld"));ob();Sb();if(!F&&n.pogoAdhesion&&(b=n.pogoAdhesion,!(b.pages&&b.pages.indexOf(T)===-1&&b.pages.indexOf(y)===-1||t.getElementById("pogo-adhesion")||t.cookie.indexOf("pogostckftrclsd")!==-1||A&&!b.mobile)&&(A||b.desktop))){var c=b.bgColor?b.bgColor:"#FAFAFA",d=c==="transparent"?"":"box-shadow: 2px -2px 2px 0px rgba(51,51,51,0.15);",e=c==="transparent"?"0":"5px 0px;",k=t.createElement("div");k.id=
"pogo-adhesion";k.classList.add("closed");d="#pogo-adhesion { display: block; background-color: "+c+"; width: 100%; max-width: 980px; position: fixed; bottom: 0px; left: 0px; transition: all 0.5s; padding: "+e+"; min-height: 50px; z-index: 123456789; "+d+" text-align:center; }#pogo-adhesion-1 { margin: auto; min-height: 50px; }#pogo-adhesion.hdn { z-index: -1; }#pogo-adhesion.closed { bottom: -125px; }#pogo-adhesion-close { cursor: pointer; position: absolute; top: -25px; left: 0px; width: 58px; height: 25px; border-top-right-radius: 5px;  background-color: "+
c+"; "+d+" }body.pgDsbld #pogo-adhesion, div.at-share-dock-outer { display: none; }@media (min-width: 768px) {#pogo-adhesion { left: 0; right: 0; margin: 0 auto; width: auto; min-width: 738px; }#pogo-adhesion-1 { min-height: 90px; }}";e=t;var m=e.createElement("style");m.type="text/css";m.styleSheet?m.styleSheet.cssText=d:m.appendChild(e.createTextNode(d));e.getElementsByTagName("head")[0].appendChild(m);c='<svg id="pogo-adhesion-close" xmlns="http://www.w3.org/2000/svg"><path d="M0,26 L0,6 A6,6 0 0,1 6,1 L50,1 A6,6 0 0,1 56,6 L56,20 A6,6 0 0,0 62,26 Z" stroke="'+
c+'" stroke-width="1" fill="'+c+'"></path><g class="down" stroke="#616161" stroke-width="2px" stroke-linecap="square"><line x1="22" y1="12" x2="28" y2="18"></line><line x1="28" y1="18" x2="34" y2="12"></line></g></svg>';typeof b.closeBtn==="undefined"||b.closeBtn||(c="");d=b.adunit?'data-adunit="'+wa("sticky",0,k.id,b.adunit)+'"':"";k.innerHTML=c+('<div id="pogo-adhesion-1" data-pogo="sticky" data-forceload="true" data-atf="true" '+(b.hidden?"":'data-showonrender="true"')+" "+d+"></div>");t.body.appendChild(k);
c!==""&&t.getElementById("pogo-adhesion-close").addEventListener("click",ib)}Tb();if(!(!n.autoPogo||F||n.disableAutopogoAds&&n.disableAutopogoAds.indexOf(T)!==-1||t.readyState&&!t.readyState.match("interactive|complete")))for(b=t.querySelectorAll("[data-autopogo]"),k=0,c=b.length;k<c;k++){m=b[k];var h=Math.round(ca[1]*(A?n.autoPogo.mobile:n.autoPogo.desktop));if(m&&h&&!(m.offsetHeight<300)&&!m.querySelector("[data-pogo='incontent'],ins.zmgad-full-width")){var g=m.children,l=n.autoPogo.insertAfterFirstPara;
m.style.position="relative";var p=new RegExp(/P|HR|Q|BLOCKQUOTE|UL|SECTION/i),r=new RegExp(/ASIDE/i),Q=new RegExp(/pogoClear|related-video|related-stories/i),H=new RegExp(/eloquent-imagery-image|twitter-tweet|roundup-review-card|roundup-product-card|lineup-card|collection-product-card|rich-text|grouped-roundup-product-card|text-card/i),D=[];d=0;for(var V=g.length;d<V;d++){e=g[d];var w=e.className||"";(e.nodeName.match(p)||w.match(H))&&D.push(e)}g=0;w=m.offsetTop;var u=t.querySelectorAll("[data-pogo=main], [data-pogo=top], [data-pogo=incontent]");
d=0;for(V=u.length;d<V;d++)if(e=u[d],e.offsetTop&&e.offsetTop<w)g=e.offsetTop;else break;w=1;e=[];u=n.autoPogo.minParaLength;var C=n.autoPogo.maxSlots?n.autoPogo.maxSlots:0;d=0;for(V=D.length;d<V;d++)if(!(m.offsetHeight<h)){var x=D[d];var P=x.offsetTop;var G=x.previousElementSibling,J=x.nextElementSibling,Da=x.className||"",Xb=J?J.className:"",Yb=G?G.className:"";v("autopogo",x,P+" / "+g+" / "+h);if(x.nodeName.match(r)||Da.match(Q)||Xb.match(Q)||Yb.match(Q))v("SKIPPING BLOCK",x,g);else if(l&&g===
0&&w===1&&d+1>=l&&x.nodeName.match(p)?(e.push([w,x,"afterend"]),g=J.offsetTop,w++,v("insertAdAfterTopPara",x,g)):G&&P-g>h&&!(G.nodeName.match(/H2|H3|H4|H5|H6|output/gi)||G.firstElementChild&&G.firstElementChild.nodeName.match(/H2|H3|H4|H5|H6/gi))&&(G.nodeName=="P"&&G.textContent.length>=u||x.nodeName==="HR"||Da.match(H))?(e.push([w,x,"beforebegin"]),g=x.offsetTop,w++,v("insertAdBefore",x,g)):J&&J.offsetTop-g>h&&(J.nodeName=="P"&&J.textContent.length>=u||J.nodeName.match(/H2|H3|H4|H5|H6|HR/gi)||Da.match(H))?
(e.push([w,x,"afterend"]),g=J.offsetTop,w++,v("insertAdAfter",x,g)):Da.match(/grouped-roundup-product-card/gi)&&P-g>h*1.85&&(e.push([w,x,"beforebegin"]),g=x.offsetTop,w++,v("insertAdBetweenProductCard",x,g)),C&&w>C)break}y!=="longform"&&D.length>0&&(w===1||n.autoPogo.insertAfterLastPara&&m.offsetHeight-g>h*.9)&&(e.push([w,m.children[m.children.length-1],"afterend"]),v("insertAdAfterLastPara",m.offsetHeight+" / "+g+" / "+h));for(d=0;d<e.length;d++)l=e[d],m=l[1],h=m.insertAdjacentElement,l=l[2],p=t.createElement("ins"),
p.classList.add("zmgad-full-width"),r=t.createElement("div"),r.dataset.pogo="incontent",r.setAttribute("data-pogo","incontent"),p.appendChild(r),h.call(m,l,p)}}pb(a);n.pogoAdhesion&&t.querySelector('[data-pogo="dialog"]')&&ib();Jb();Ea()}function ia(a){v("Full RunPogo invoked - Resetting page");(q&&Object.keys(q).length||z&&Object.keys(z).length)&&Vb();gb=Math.floor(Math.random()*1E7);T=f.location.pathname;ra=!1;N=null;f.__ZD_CPID_&&(f.__ZD_CPID_="");Ca||Na();a=L(a);Ea();return a}function Ea(){var a=
t.querySelector('[data-pogo="outstream"]');!F&&a&&(a.className.match(/pgIgnore|pgConnatix|pgPrimis/)||(f.PogoOutstream&&f.PogoOutstream.init?setTimeout(f.PogoOutstream.init,100):W("https://pg.ziffstatic.com/pgout.js",function(){f.PogoOutstream.init()})))}function Zb(){if(n.zdcoreConversions&&f.__ZDCoreConversion)for(var a=Object.keys(n.zdcoreConversions),b=0;b<a.length;b++)if(T.indexOf(a[b].toLowerCase())===0)try{f.__ZDCoreConversion(n.zdcoreConversions[a[b]])}catch(c){console.log(c)}}function Oa(){v("initPageConfig invoked");
Ua();a:{try{ca=[t.documentElement.clientWidth,t.documentElement.clientHeight];break a}catch(g){}ca=[f.screen.width,f.screen.height]}var a;T=f.location.pathname.toLowerCase();ea=da.indexOf(".zdtc.global")!==-1?"https://speedtest.com"+T:f.location.href;f.google_page_url||(f.google_page_url=ea);(xa=T.split("/").pop().split(".")[0].toLowerCase())||(xa="homepage");if(f.PogoConfig||t.body){y=E="general";f.gaTemplate&&(y=f.gaTemplate);if(a=f.PogoConfig?f.PogoConfig:t.body.dataset)if(a.template?y=La(a.template):
a.gaTemplate&&(y=La(a.gaTemplate)),a.category&&(E=La(a.category)),a.tags){var b=Ma(a.tags);b&&b.length&&(N=b)}y===""&&f.object_type&&(y=f.object_type);b=[];var c=t.querySelector('meta[name="keywords"]');c&&c.getAttribute("content");c={};for(var d in c)if(c.hasOwnProperty(d)&&d){var e=c[d];d=d.toUpperCase();if(t.title&&t.title.toUpperCase().indexOf(d)!==-1)b.indexOf(d)===-1&&b.push(e);else for(var k=t.querySelectorAll?t.querySelectorAll("h1,h2,h3,[rel=tag]"):t.getElementsByTagName("h1"),m=0;m<k.length;m++)if(b.indexOf(d)===
-1){var h=k[m];h.textContent&&h.textContent.toUpperCase().indexOf(d)!==-1&&b.indexOf(d)===-1&&b.push(e)}}b.length&&(N=b=N?Ma(N.concat(b)):Ma(b));T==="/"&&(a&&a.template||(y="homepage"),a&&a.category||(E="homepage"));a=f.location.pathname;a.indexOf("/result/")!==-1||t.querySelector(".layout-mobile .mobile-test-complete, .layout-mobile .result-container-speed-active")?y=t.querySelector("div.result-container-speed.result-container-speed-active, div.gauge-wrapper, a.btn-restart-test, .layout-mobile .mobile-test-complete, .layout-mobile .result-container-speed-active")?
"results":"share":(a.endsWith("/run"),y="homepage");lb();a=f.OOKLA.globals;d=a.configs;b=f.dataLayer;e=c=null;if(b)for(k=0;k<b.length;k++)b[k]&&(b[k].downloadSpeed&&(c=Ub(b[k].downloadSpeed)),b[k].ping&&(e=jb(b[k].ping)),b[k].resultId&&jb(b[k].resultId));n.pageTargeting={stIspId:a.ispId,stOutage:d.outages,country:S,household_carrier:d.householdCarrier?d.householdCarrier:"other",hostname:f.location.origin,bucket_test:$b,stDownloadSpeed:c,stLatency:e};F=!1;d.ads===!1&&(F=!0);nb&&t.body.classList.add("pgAB");
y&&(y=sa(y));a=!0}else a=!1;if(!a)return!1;Z&&(n.disableSRA=!1);qa&&(n.dv=!1);ra=!0;U(qb);(f.pbjs||n.prebid)&&Xa()}function Na(){if(Ca)L();else{Ca=!0;Ha.indexOf("Trident")!==-1&&(n.prebid=!1,n.amazon=!1,n.dv=!1);B.indexOf("pogonoprog")!==-1&&(n.prebid=!1,n.amazon=!1,n.dv=!1,n.collapse=!0,t.body&&t.body.classList.add("pgCollapse","pgNoProg"),n.pageTargeting||(n.pageTargeting={}),n.pageTargeting.noprogrammatic="true");B.indexOf("no_aps")!==-1&&(n.amazon=!1);B.indexOf("noadrefresh")!==-1&&(n.autorefresh=
!1);f.googletag=f.googletag||{cmd:[]};ra||Oa();f.googletag.cmd.push(ac);f.googletag.apiReady||t.querySelector('script[src*="https://5ddUbRej3v4W.net/tag/js/V9l333o3R0bx.js"]')||W("https://5ddUbRej3v4W.net/tag/js/V9l333o3R0bx.js");n.prebid?(f.pbjs=f.pbjs||{que:[]},f.pbjs.version||W("https://omvvZfF1F7RV.com/pg/speedtest.prebid.js"),Db()):W("https://omvvZfF1F7RV.com/pg/speedtest.prebid.js");!n.amazon||n.prebid||f.ID5||W("https://cdn.id5-sync.com/api/1.0/id5-api.js",function(){ID5.init({partnerId:n.id5,
provider:"aps"})});n.dv&&!f.dvtag&&(f.dvtag=f.dvtag||{},f.dvtag.cmd=f.dvtag.cmd||[],W("https://pub.doubleverify.com/dvtag/"+n.dv+"/pub.js"));B.indexOf("pogodemo=")===-1&&B.indexOf("special=")===-1||f.PogoAdkit||W("https://pg.ziffstatic.com/pogoadkit.js");B.indexOf("special=pogoquickslider")===-1||n.pogoMasthead||(n.pogoMasthead=!0);if(n.libs)for(var a=0;a<n.libs.length;a++)W(n.libs[a]);f.addEventListener&&(f.addEventListener("message",function(b){(b=b.data)&&b.event&&(b.event==="stopadrefresh"&&b.name?
la([b.name]):b.event==="pogodestroyslot"&&b.name?Aa([b.name]):b.event==="hideadvlabel"&&b.name?Wb([b.name]):b.event==="pogodetectnewadslots"?setTimeout(L,1):b.event==="pogorun"?setTimeout(ia,1):b.event==="pogodeb"?wb(b.idx):b.event==="pogopause"&&la())},!1),f.addEventListener("pogorun",function(b){b.details&&(f.PogoConfig=f.PogoConfig||{},f.PogoConfig.pageMeta=b.details);ia()},!1),f.addEventListener("pogodetectnewadslots",function(){setTimeout(L,1)},!1),f.addEventListener("hashchange",function(){f.location.hash.indexOf("#pogodeb")===
0&&xb()}));bc();Zb();f.__PogoExcoYieldSDK&&setTimeout(f.__PogoExcoYieldSDK,100)}}function rb(){pa&&(t.readyState&&t.readyState.match("interactive|complete")?L():t.addEventListener&&(t.addEventListener("DOMContentLoaded",function(){v("Run Pogo after DOMContentLoaded");setTimeout(L,20)},!1),t.body&&(v("QuickRun Pogo before DOMContentLoaded"),L())))}function ac(){var a=f.googletag.pubads();a.disableInitialLoad();a.enableAsyncRendering();a.setCentering(!0);a.addEventListener("slotRenderEnded",sb);a.addEventListener("impressionViewable",
cc);qb();if(n.lazyload){var b=n.lazyload!==!0?n.lazyload:{fetchMarginPercent:800,renderMarginPercent:300,mobileScaling:2};f.googletag.pubads().enableLazyLoad(b)}t.cookie.indexOf("opt_out=1")!==-1&&a.setPrivacySettings({nonPersonalizedAds:!0,restrictDataProcessing:!0});Z&&(n.disableSRA=!1);n.disableSRA||a.enableSingleRequest();googletag.enableServices();v("Pogo GPT bootstrap completed")}function tb(a){var b=t.getElementById(a);if(!b)return!1;var c=b&&b.dataset&&b.dataset.pogoFallback?b.dataset.pogoFallback:
!1;if(c)c=c.split(" ")[0];else return!1;return c==="outstream"?(Aa([a]),b.setAttribute("data-pogo","outstream"),b.className="",setTimeout(Ea,100),!0):c==="refresh"?(setTimeout(function(){ja([a])},350),!0):!1}function sb(a){var b=a.slot,c=b.getSlotElementId();v("GPT Slot Rendered",c,a);z[c]&&!z[c].numRendered&&(z[c].numRendered=1,z[c].isEmpty=a.isEmpty);if(c==="pogo-quickslider"&&(!a.creativeId||b.getHtml().indexOf(': "PogoAdkit"')===-1)){z[c].isEmpty=!0;try{t.getElementById(c).style.display="none"}catch(e){}}if(q[c]){q[c].amazonStatus&&
(q[c].amazonStatus=1);q[c].prebidStatus&&(q[c].prebidStatus=1);if(q[c].isEmpty=a.isEmpty){if(tb(c))return;if(q[c].isEmpty&&q[c].refreshOnEmpty&&q[c].refreshOnEmptyCounter<3&&!q[c].autorefreshTimeout){a=3E3+Math.floor(Math.random()*4E3);q[c].refreshOnEmptyCounter>1&&(a=3500*(q[c].refreshOnEmptyCounter+1));v("Force an adslot refresh for empty slot in "+a/1E3+"s",c);q[c].autorefreshTimeout=setTimeout(function(){ja([b])},a);q[c].refreshOnEmptyCounter+=1;q[c].targeting.rfre=q[c].refreshOnEmptyCounter;
return}}else q[c].targeting.rfre=null;q[c].renderedAt=Math.floor(Date.now()/1E3);if(!a.isEmpty&&q[c].showOnRender){var d=document.getElementById(c);d&&(d.classList.contains("closed")&&d.classList.remove("closed"),d.parentNode&&d.parentNode.classList.contains("closed")&&d.parentNode.classList.remove("closed"))}a.advertiserId&&n.nondirectAdvertiserIds&&n.nondirectAdvertiserIds.indexOf(a.advertiserId)===-1?q[c].isNonDirect=!1:q[c].isNonDirect=!0;v("New creative rendered succesfully",c,a)}}function cc(a){var b=
a.slot,c=b.getSlotElementId();v("GPT Slot Viewable",c,a);if(q[c]){q[c].renderedAt||sb(a);var d=Math.floor(Date.now()/1E3);q[c].viewableAt=d;q[c].autorefreshTimeout&&(f.clearTimeout(q[c].autorefreshTimeout),q[c].autorefreshTimeout=null);a.isEmpty||(a=q[c].autorefresh?q[c].autorefresh:0,!a&&q[c].isNonDirect&&q[c].autorefreshNonDirectOnly&&(a=q[c].autorefreshNonDirectOnly),a&&(d=a-(d-q[c].renderedAt),d<0?ja([b]):(q[c].autorefreshTimeout=setTimeout(function(){ja([b])},d*1E3),v("Slot scheduled for autorefresh in "+
d+" secs",c))));if(f.__pogoViewableCallback)try{f.__pogoViewableCallback({elementId:c,gptSlot:b,pogoConfig:q[c]})}catch(e){}}}function ub(a){var b=typeof a;if(a&&b!=="boolean"&&!a.__processed){try{b==="string"?W(a):setTimeout(a,0)}catch(c){console.log("Pogo queue error",c,a)}a.__processed=!0}}function bc(){f.Pogo||(f.Pogo={cmd:[]});f.Pogo.cmd||(f.Pogo.cmd=[]);for(var a=0,b=f.Pogo.cmd.length;a<b;a++)ub(f.Pogo.cmd[a]);f.Pogo.cmd.__processed=!0;f.Pogo.cmd.push=ub;return!0}if(!f.Pogo||!f.Pogo.inited){var vb=
new Date,A=f.screen.width<=640?!0:!1;!A&&f.innerWidth<=640&&(A=!0);var B=f.location&&f.location.search?f.location.search.toLowerCase():"",Ha=f.navigator&&f.navigator.userAgent?f.navigator.userAgent:"",da=f.location&&f.location.hostname?f.location.hostname.toLowerCase():"",t=f.document,ba=A?1250:1E3,T=f.location.pathname.toLowerCase(),ca=null,y="",E="",xa="",N=null,ea="",Z=!1,Ia=!1,ra=!1,Ca=!1,qa=null,ma=!1,Wa=f.zdconsent||t.querySelector('script#zdconsent,script[src*="zdconsent"]')?!0:!1;Wa&&(f.zdconsent=
f.zdconsent||{run:[],cmd:[],useractioncomplete:[],analytics:[],functional:[],social:[]},"run cmd useractioncomplete analytics functiona social".split(" ").forEach(function(a){f.zdconsent[a]||(f.zdconsent[a]=[])}));var S=null,aa=!1,va="",I=!1,Ja=!1,eb=["prebid","amazon","dv"],gb=Math.floor(Math.random()*1E7),M={site:"596 599 600 602 619 626 618".split(" "),kwarray:"ookla;speed;test;speedtest;bandwidth;internet speed;broadband;internet;network;connection;latency;ping;download;upload;connection;dsl;adsl;cable;isp;voip;ip;ip address;tcp".split(";"),
context:4},n={dfp:"/6692/speedtest.net/#ID",OOPs:null,delayBootstrap:0,pogoMasthead:!1,pogoInterscroller:{slots:["incontent","main"],num:1},pogoSkin:!1,autorefresh:!1,prebid:{openx:{id:538306129},rubicon:{accountId:11576,siteId:79558,id:373684},ix:{id:184382},appnexus:{id:7724467},pubmatic:{id:159017,adSlot:"stnext_leaderboard"},sharethrough:{id:"rmWgQEnhuz7ij4zskq9giJxW"},criteo:{id:11834},yahooAds:{id:"stnext_leaderboard_728x90",dcn:"8a969009017373bfc8dcc112d91b00af"},medianet:{id:"8CUYEJ1S6",crid:"498162527"}},
amazon:3336,dv:!1,id5:718,pageTargeting:null,lazyload:!1,disableSRA:!1,collapse:!1,refreshOnEmpty:5,autoPogo:{desktop:1.2,mobile:1.2,minParaLength:250,insertAfterFirstPara:!1,insertAfterLastPara:!0},disableAds:null,enableAmazonCommerce:null,disableAutopogoAds:null,zdcoreConversions:null,libs:[],nondirectAdvertiserIds:[-1,4889004171,103662002,5200925960,16425242,4861924994,4882357101,4882357101,4862631028,82658162,5789990395],video:{sz:"640x480|640x360",iu:"/4585/mashable",ad_rule:0,gdfp_req:1,env:"vp",
output:"vast",unviewed_position_start:1,min_ad_duration:1,max_ad_duration:3E5,sdmax:3E5,vad_type:"linear",vpos:"preroll",tcfd:0,cmsid:"%%CMS_ID%%",vid:"%%VIDEO_ID%%",cust_params:{channel:"null",keywords:[],playtype:"auto",pogo:"video"},afvsz:"300x250,728x90",aconp:1,vconp:1,vpa:"click",plcmt:1,trt:2,correlator:"[placeholder]"},autorefreshNonDirectOnly:0,amazonCommerce:!1,otcTracker:"https://cc.zdtc.app/v1/otc/025HJQYBAMaMQ2SMbceddgb?url=",prebidLiveIntentId:78658},K={top:{sizes:{"768x200":[[728,90],
[320,100],[320,50],[300,50],[300,100]],"0x0":[[320,50],[300,50],[320,100],[300,100]]}},main:{sizes:{"768x300":[[728,90],[320,50],[320,100],[300,50],[300,100]],"0x0":[[300,250],[336,280],[320,50],[300,50],[320,100],[300,100],[200,200],[250,250]]}},incontent:{sizes:{"750x200":[[728,90]],"0x0":[[300,250],[320,50],[300,100],[320,100]]}},sidebar:{sizes:{"768x200":[[300,250],[300,50],[300,100],[200,200],[250,250]],"0x0":[[300,250],[300,50],[300,100],[300,50],[200,200],[250,250]]}},comments:{sizes:{"0x0":[[300,
250]]}},footer:{sizes:{"768x300":[[970,250],[970,200],[970,180],[970,90],[728,90],[200,200],[250,250]],"0x0":[[300,250],[336,280],[320,50],[300,50],[320,100],[300,100],[200,200],[250,250]]}},dialog:{sizes:{"0x0":[[336,280],[300,250],[300,100],[200,200],[250,250]]}},largerec:{sizes:{"700x200":[[336,280],[300,250]],"0x0":[[300,250],[300,600]]}},"native":{sizes:"fluid",refreshOnEmpty:!1,autorefresh:!1,prebid:!1,amazon:!1},nativespotlight:{sizes:{"0x0":[[120,240]]},refreshOnEmpty:!1,autorefresh:!1,prebid:!1,
amazon:!1},sticky:{sizes:{"0x0":[[320,50],[300,50],[320,100],[300,100]]}},stnext_skyscraper:{sizes:{"1440x200":[[160,600],[120,600]],"768x200":[[160,600],[120,600]],"0x0":[[300,250],[320,50],[300,50],[320,100]]}},results_stnext_right_300x600:{sizes:{"768x200":[[300,250],[300,600],[160,600],[200,200],[250,250]],"0x0":[[300,250],[300,100],[200,200],[250,250]]}}},q={},z={},pa=!0,F=!1,Y=f.__PogoDebug||B.indexOf("pogodebug")!==-1||t.cookie.indexOf("pogodebug=")!==-1?1:!1;B.match(/pogodebug=([0-9])/i)?
Y=parseInt(B.match(/pogodebug=([0-9])/i)[1]):t.cookie.match(/pogodebug=([0-9])/i)&&(Y=parseInt(t.cookie.match(/pogodebug=([0-9])/i)[1]));var Ra=[],na=!1,Za={},mb=!1,Ba=!1,nb=!1,$b=Math.floor(Math.random()*20+1),Pa={inited:!0,initPageConfig:Oa,run:ia,geoCC:function(){return S},setGeo:Va,setGeoCC:Va,detectNewAdslots:function(){setTimeout(L,10)},runOutstream:Ea,adslotFallback:tb,setupAdslots:pb,destroyAdslots:Aa,canRenderAds:Ka,renderAds:ka,refreshAds:ja,stopAutorefresh:la,getVideoTag:za,getJWPlayerConfig:function(a,
b,c){if(F)return c?c(b,!0):b;b||(b={});a||(a={});typeof a.playType==="undefined"&&b.autostart&&(a.playType=b.autostart===!1?"click":"autostart");a.videoId&&b.mediaid&&(a.videoId=b.mediaid);typeof a.isMuted==="undefined"&&typeof b.mute!=="undefined"&&(a.isMuted=b.mute);b.advertising={client:"googima",loadVideoTimeout:4E3,locale:"en",skipoffset:5,preloadAds:!0,schedule:[{offset:"pre",tag:""}],rules:{startOn:1,frequency:2}};if(c)za(a,function(d,e){e&&(b.advertising.schedule[0].tag=d);c(b,!0)});else return b.advertising.schedule[0].tag=
za(a),b},getExcoVideoTag:fb,getExcoVideoConfig:function(a){if(F)return a?(a.showAds=!1,a):null;var b={id:"614921260",urlGenerator:{fn:fb,timeout:ba*1.5,async:!0}};return a?(a.vast=b,a):b},setADB:function(a){if(a!==qa&&(qa=a?!0:!1)){n.amazonCommerce=!1;if(window._aps)try{Ia=!1,window._aps.get(""+n.amazon).queue=window._aps.get(""+n.amazon).queue.slice(0,3)}catch(b){}ia()}},_enableDebug:function(a){Y=Y||1;t.cookie="pogodebug="+Y+";path=/;"},siteId:"speedtest",getMeta:function(){return{template:y,category:E,
tags:N,adslots:q,oops:z,adsDisabled:F}}};f.Pogo||(f.Pogo={cmd:[]});for(var Qa in Pa)Pa.hasOwnProperty(Qa)&&(f.Pogo[Qa]=Pa[Qa]);ua();if(f.PogoConfig){if(f.PogoConfig.isDiscourse){pa=!1;n.pogoMasthead="top";return}f.PogoConfig.autostart===void 0||f.PogoConfig.autostart||(pa=!1)}setTimeout(Na,0);t.readyState&&t.readyState.match("interactive|complete")?setTimeout(rb,1):t.addEventListener("DOMContentLoaded",function(){setTimeout(rb,1)},!1)}})(window);

